/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.Dao_NhanVien;
import dao.Dao_TaiKhoan;
import entity.NhanVien;
import entity.SanPham;

/**
 *
 * @author TuanPC
 */
public class GUI_NhanVien extends javax.swing.JPanel implements ActionListener{
	public static int edit = 0;
	private Dao_TaiKhoan dao_TaiKhoan = new Dao_TaiKhoan();
    /**
     * Creates new form NV
     */
    public GUI_NhanVien() {
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException ex) {
        }    
            initComponents();
            dao_NhanVien = new Dao_NhanVien();
            updataTable();
            tableNhanVien.addMouseListener(new MouseListener() {
    			
    			@Override
    			public void mouseReleased(MouseEvent e) {
    				// TODO Auto-generated method stub
    				
    			}
    			
    			@Override
    			public void mousePressed(MouseEvent e) {
    				// TODO Auto-generated method stub
    				
    			}
    			
    			@Override
    			public void mouseExited(MouseEvent e) {
    				// TODO Auto-generated method stub
    				
    			}
    			
    			@Override
    			public void mouseEntered(MouseEvent e) {
    				// TODO Auto-generated method stub
    				
    			}
    			
    			@Override
    			public void mouseClicked(MouseEvent e) {
    				if(SwingUtilities.isRightMouseButton(e)) {
    					int r = tableNhanVien.rowAtPoint(e.getPoint());
    					if (r >= 0 && r < tableNhanVien.getRowCount()) {
    						tableNhanVien.setRowSelectionInterval(r, r);
    					} else {
    						tableNhanVien.clearSelection();
    					}
    					int rowselect = tableNhanVien.getSelectedRow();
    					if (rowselect < 0)
    						return;
    					else {
    						popSP.show(e.getComponent(),e.getX(),e.getY());
    					}
    				}
    			}
    		});	
            btnThem.addActionListener(this);
            btnXoa.addActionListener(this);
            btnSua.addActionListener(this);
            btnTim.addActionListener(this);
            btnLamMoi.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimHoTen = new javax.swing.JTextField();
        txtTimsdt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTimCCCD = new javax.swing.JTextField();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        chkTimHoTen = new javax.swing.JCheckBox();
        chkTimSDT = new javax.swing.JCheckBox();
        chkTimCCCD = new javax.swing.JCheckBox();
        btnTim = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1426, 722));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Nhân Viên");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm"));

        jLabel2.setText("Tìm họ tên: ");

        jLabel6.setText("Tim sdt: ");

        jLabel7.setText("Tìm cccd: ");

        jLabel8.setText("Tìm giới tính: ");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả","Nam", "Nữ" }));

        btnTim.setBackground(new java.awt.Color(51, 153, 255));
        btnTim.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon("img\\timkiem24.png")); // NOI18N
        btnTim.setText("Tìm Kiếm");

        btnLamMoi.setBackground(new java.awt.Color(51, 153, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\refresh24.png")); // NOI18N
        btnLamMoi.setText("Làm mới");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkTimSDT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkTimHoTen)))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTimCCCD)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTimHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkTimHoTen)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimsdt)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(chkTimSDT))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimCCCD)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(chkTimCCCD))
                            .addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(cbbGioiTinh)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách nhân viên"));

        tableNhanVien.setModel(modelNhanVien=new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "Ngày Sinh", "Giới Tính ", "Số điện thoại", "CCCD", "Xã/Phường","Quận/Huyện","Tỉnh/Thành Phố", "Chức Vụ"
            }
        ));
        tableNhanVien.setRowHeight(30);
        tableNhanVien.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(tableNhanVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        btnThem.setBackground(new java.awt.Color(51, 153, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon("img\\add.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 153, 255));
        btnSua.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon("img\\fix.png")); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 153, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon("img\\delete.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(btnThem)
                .addGap(57, 57, 57)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JCheckBox chkTimCCCD;
    private javax.swing.JCheckBox chkTimHoTen;
    private javax.swing.JCheckBox chkTimSDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField txtTimCCCD;
    private javax.swing.JTextField txtTimHoTen;
    private javax.swing.JTextField txtTimsdt;
    public static DefaultTableModel modelNhanVien;
    public static Dao_NhanVien dao_NhanVien;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if(o.equals(btnThem)) {
                    GUI_ThemNhanVien gui_themNV = new GUI_ThemNhanVien();
                    gui_themNV.setVisible(true);
                    gui_themNV.setLocationRelativeTo(null);
                    gui_themNV.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    edit = 1;
		}else if(o.equals(btnXoa)) {
			if(tableNhanVien.getSelectedRow()!=-1) {
				if(JOptionPane.showConfirmDialog(this, "Có chắc chắn xóa không","Cảnh báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
					dao_NhanVien.xoaNhanVien(modelNhanVien.getValueAt(tableNhanVien.getSelectedRow(), 0).toString());
					modelNhanVien.removeRow(tableNhanVien.getSelectedRow());
					JOptionPane.showMessageDialog(this, "Xóa thành công");
				}
			}else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên cần xóa");
			}
		}else if(o.equals(btnSua)) {
			int row = tableNhanVien.getSelectedRow();
			if(row!=-1) {
				GUI_ThemNhanVien gui_SuaNV = new GUI_ThemNhanVien();
				gui_SuaNV.setVisible(true);
				gui_SuaNV.setLocationRelativeTo(null);
				gui_SuaNV.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
				gui_SuaNV.getLbMaNV().setText(modelNhanVien.getValueAt(row, 0).toString());
				gui_SuaNV.getCbbGioiTinh().setSelectedItem(modelNhanVien.getValueAt(row, 3).toString());
				gui_SuaNV.getCbbChucVu().setSelectedItem(modelNhanVien.getValueAt(row, 9).toString());
				gui_SuaNV.getCbbTinhTP().setSelectedItem(modelNhanVien.getValueAt(row, 8).toString());
				gui_SuaNV.getCbbQuanHuyen().setSelectedItem(modelNhanVien.getValueAt(row, 7).toString());
				gui_SuaNV.getCbbPhuongXa().setSelectedItem(modelNhanVien.getValueAt(row, 6).toString());
				gui_SuaNV.getJcNgaySinhNV().setDate((java.util.Date) modelNhanVien.getValueAt(row, 2));
				gui_SuaNV.getTxtCCCD().setText(modelNhanVien.getValueAt(row, 5).toString());
				gui_SuaNV.getTxtSDT().setText(modelNhanVien.getValueAt(row, 4).toString());
				gui_SuaNV.getTxtTenNV().setText(modelNhanVien.getValueAt(row, 1).toString());
				edit=2;
			}else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên cần sửa");
			}
			
		}else if(o.equals(btnTim)) {
			String hoT = "%"+txtTimHoTen.getText().trim()+"%";
			String sdt = "%"+txtTimsdt.getText().trim()+"%";
			String cccd = "%"+txtTimCCCD.getText().trim()+"%";
			String gt = cbbGioiTinh.getSelectedItem().toString() == "Nam" ? "0" : "1"; 
			if(cbbGioiTinh.getSelectedIndex()==0) {
				gt = "";
			}
			if(chkTimHoTen.isSelected())
				hoT = txtTimHoTen.getText().trim();
			if(chkTimSDT.isSelected())
				sdt = txtTimsdt.getText().trim();
			if(chkTimCCCD.isSelected())
				cccd = txtTimCCCD.getText().trim();
			if(txtTimHoTen.getText().trim().equals(""))
				hoT = "%%";
			if(txtTimsdt.getText().trim().equals(""))
				sdt = "%%";
			if(txtTimCCCD.getText().trim().equals(""))
				cccd = "%%";
			modelNhanVien.setRowCount(0);
			for(NhanVien nv : dao_NhanVien.getNhanVienTheoDK(hoT,sdt,cccd,gt)) {
				String p = "Nam";
				if(nv.isGioiTinh()) p="Nữ";
				Object row [] = {nv.getMaNhanVien(),nv.getHoTen(),nv.getNgaySinh(),p,nv.getSdt(),nv.getCccd(),nv.getDiaChi().getPhuongXa(),nv.getDiaChi().getQuanHuyen(),nv.getDiaChi().getTinhTP(),nv.getChucVu()};
				modelNhanVien.addRow(row);
			}
		}else if(o.equals(btnLamMoi)) {
			txtTimCCCD.setText("");
			txtTimHoTen.setText("");
			txtTimsdt.setText("");
			chkTimCCCD.setSelected(false);
			chkTimHoTen.setSelected(false);
			chkTimSDT.setSelected(false);
			cbbGioiTinh.setSelectedIndex(0);
			updataTable();
		}
	}
	public static void updataTable() {
		modelNhanVien.setRowCount(0);
		for(NhanVien nv : dao_NhanVien.getAllNhanVien()) {
			String p = "Nam";
			if(nv.isGioiTinh()) p="Nữ";
			Object row [] = {nv.getMaNhanVien(),nv.getHoTen(),nv.getNgaySinh(),p,nv.getSdt(),nv.getCccd(),nv.getDiaChi().getPhuongXa(),nv.getDiaChi().getQuanHuyen(),nv.getDiaChi().getTinhTP(),nv.getChucVu()};
			modelNhanVien.addRow(row);
		}
	}
	public class RightClickPopUp extends JPopupMenu{
		public RightClickPopUp(JTable table) {
	    	
	        JMenuItem themTK = new JMenuItem("Tạo Tài Khoản");
	        JMenuItem xoa = new JMenuItem("Xóa Tài Khoản");
	    	
	        themTK.addActionListener(new ActionListener() {
				
				@Override
				public void actionPerformed(ActionEvent e) {
					if(dao_TaiKhoan.getAllTaiKhoan().contains(modelNhanVien.getValueAt(tableNhanVien.getSelectedRow(), 0))) {
						JOptionPane.showMessageDialog(null, "Nhân viên đã có tài khoản");
					}else {
						GUI_TaoTaiKhoan gui_TaoTaiKhoan = new GUI_TaoTaiKhoan();
						gui_TaoTaiKhoan.setVisible(true);
						gui_TaoTaiKhoan.setLocationRelativeTo(null);
						gui_TaoTaiKhoan.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
						gui_TaoTaiKhoan.getLbTaiKhoan().setText(modelNhanVien.getValueAt(tableNhanVien.getSelectedRow(), 0).toString());
					}
				}
			});
	        xoa.addActionListener(new ActionListener() {
				
				@Override
				public void actionPerformed(ActionEvent e) {
					if(JOptionPane.showInternalConfirmDialog(null, "Bạn có chắc chắn muốn xóa không.","Cảnh báo",  JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
						if(GUI_DangNhap.getTxtTaiKhoan().getText().equals(modelNhanVien.getValueAt(tableNhanVien.getSelectedRow(), 0).toString())) {
							JOptionPane.showMessageDialog(null, "Tài khoản đang đăng nhập không thể xóa");
						}else {
							dao_TaiKhoan.xoaTaiKhoan(modelNhanVien.getValueAt(tableNhanVien.getSelectedRow(), 0).toString());
							JOptionPane.showMessageDialog(null, "Xóa thành công");	
						}
					}
					
				}
			});
	        add(themTK);
	        add(xoa);
	    }
	}
	private RightClickPopUp popSP = new RightClickPopUp(tableNhanVien);
}
