/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import connectDB.ConnectDB;
import dao.Dao_LoaiSanPham;
import dao.Dao_NhaCungCap;
import dao.Dao_NhaXuatBan;
import dao.Dao_PhatSinhMa;
import dao.Dao_SanPham;
import dao.Dao_TacGia;
import entity.LoaiSanPham;
import entity.NhaCungCap;
import entity.NhaXuatBan;
import entity.SanPham;
import entity.TacGia;
import entity.XuatXu;

/**
 *
 * @author TuanPC
 */
public class GUI_ThemSach extends javax.swing.JFrame implements ActionListener{
	private Dao_PhatSinhMa dao_PhatSinhMa;
	private static Dao_SanPham dao_SanPham= new Dao_SanPham();
	private static Dao_LoaiSanPham dao_LoaiSanPham = new Dao_LoaiSanPham();
	private static Dao_TacGia dao_TacGia = new Dao_TacGia();
	private static Dao_NhaCungCap dao_NhaCungCap = new Dao_NhaCungCap();
	private static Dao_NhaXuatBan dao_NhaXuatBan = new Dao_NhaXuatBan();
    /**
     * Creates new form GUI_ThemSach
     */
    public GUI_ThemSach() {
dao_PhatSinhMa = new Dao_PhatSinhMa();
		
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		initComponents();
		ArrayList<LoaiSanPham> dataList = dao_LoaiSanPham.getLoaiSach();
		for(LoaiSanPham loaisp : dataList) {
			cbbLoaiSach.addItem(loaisp.getChiTiet());
		}
		ArrayList<NhaCungCap> listNCC = dao_NhaCungCap.getAllNCC();
		for (NhaCungCap nhaCungCap : listNCC) {
			cbbNCC.addItem(nhaCungCap.getTenNCC());
		}
		ArrayList<TacGia> listTG = dao_TacGia.getAllTG();
		for (TacGia tacGia : listTG) {
			cbbTacGia.addItem(tacGia.getHoTen());
		}
		ArrayList<NhaXuatBan> listNXB = dao_NhaXuatBan.getAllNXB();
		for (NhaXuatBan nhaXuatBan : listNXB) {
			cbbNhaXB.addItem(nhaXuatBan.getTenNXB());
		}
		lbMa.setText(dao_PhatSinhMa.getMaSP());
		lbMa.setForeground(Color.white);
		lbMa.setFont(new Font("Arial", Font.BOLD, 16));
		btnXacNhan.addActionListener(this);
		btnHuy.addActionListener(this);
		btnLamMoi.addActionListener(this);
		btnChonAnh.addActionListener(this);
		lbAnh.setIcon(ResizeImage(String.valueOf("img/macdinh.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        txtNamXB = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cbbLoaiSach = new javax.swing.JComboBox<>();
        cbbTacGia = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtGiaNhap = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        lbAnh = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtSoTrang = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cbbNhaXB = new javax.swing.JComboBox<>();
        cbbNCC = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 119, 221));

        jLabel21.setBackground(new java.awt.Color(153, 204, 255));
        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Thêm Sách");

        jLabel22.setBackground(new java.awt.Color(153, 204, 255));
        jLabel22.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nhà Sách Thiên Văn");

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mã sách:");

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tên Sách:");

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Số lượng: ");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tác Giả:");

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Năm Xuất Bản:");

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Giá nhập: ");

        lbMa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMa.setForeground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Loại Sách:");

        btnXacNhan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(51, 102, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon("img\\yes24.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");

        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(51, 102, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\rf24.png")); // NOI18N
        btnLamMoi.setText("Làm Mới");

        btnHuy.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(51, 102, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon("img\\huy24.png")); // NOI18N
        btnHuy.setText("Hủy");

        lbAnh.setBackground(new java.awt.Color(255, 255, 255));

        btnChonAnh.setText("Chọn Ảnh");

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Số Trang:");

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Mô Tả:");

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Nhà Cung Cấp:");

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Nhà Xuất Bản:");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenSach))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamXB))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMa, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoTrang)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbTacGia, javax.swing.GroupLayout.Alignment.TRAILING, 0, 235, Short.MAX_VALUE)
                            .addComponent(cbbLoaiSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnLamMoi)
                        .addGap(20, 20, 20)
                        .addComponent(btnXacNhan))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbNCC, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbNhaXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbbNhaXB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(554, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ThemSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbbLoaiSach;
    private javax.swing.JComboBox<String> cbbNCC;
    private javax.swing.JComboBox<String> cbbNhaXB;
    private javax.swing.JComboBox<String> cbbTacGia;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbMa;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTenSach;
    private String duongDanAnh = "img/macdinh.png";
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if(o.equals(btnChonAnh)) {
			try {
				JFileChooser f = new JFileChooser("img");
				f.setDialogTitle("Mở file");
				f.showOpenDialog(null);
				File ftenAnh = f.getSelectedFile();
				duongDanAnh = ftenAnh.getAbsolutePath();
				lbAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
			} catch (Exception ex) {
			}
		}else if(o.equals(btnXacNhan)) {
			if(validData()) {
			String maSP = lbMa.getText();
			String tenSP = txtTenSach.getText().trim();
			int soLuong = Integer.parseInt(txtSoLuong.getText().trim());
			double giaNhap = Double.parseDouble(txtGiaNhap.getText().trim());
			int namXB = Integer.parseInt(txtNamXB.getText().trim());
			int soTrang = Integer.parseInt(txtSoTrang.getText().trim());
			String nxb = cbbNhaXB.getSelectedItem().toString();
			String tg = cbbTacGia.getSelectedItem().toString();
			String ncc = cbbNCC.getSelectedItem().toString();
			String moTa = txtMoTa.getText().trim();
			String lsp = cbbLoaiSach.getSelectedItem().toString(); 
			SanPham sp = new SanPham(maSP, tenSP, soLuong, giaNhap, namXB, soTrang, 
					new NhaXuatBan(dao_NhaXuatBan.getMaNXBTheoTen(nxb)), 
					new TacGia(dao_TacGia.getMaTheoTen(tg)), moTa,duongDanAnh, 
					new LoaiSanPham(dao_LoaiSanPham.getMaTheoChiTietLoai(lsp)) , 
					new NhaCungCap(dao_NhaCungCap.getMaNCCTheoTen(ncc)));
			if(GUI_Sach.edit==1) {
			
					if (dao_SanPham.themSach(sp)) {
						JOptionPane.showMessageDialog(null, "Thêm thành công " + tenSP);
						GUI_Sach.updateTable();
						dispose();
					} else if(!dao_SanPham.themSach(sp)) {
						JOptionPane.showMessageDialog(null,"Thêm chưa thành công");
					}
					
			}else if(GUI_Sach.edit==2) {
				
					if (dao_SanPham.suaSach(sp)) {
						JOptionPane.showMessageDialog(null, "Sửa thành công " + tenSP);
						GUI_Sach.updateTable();
						dispose();
					} 
					else if(!dao_SanPham.suaSach(sp)) {
						JOptionPane.showMessageDialog(null,"Sửa chưa thành công");
					}
				}
			}
		}else if(o.equals(btnHuy)) {
			dispose();
		}else if(o.equals(btnLamMoi)) {
			txtTenSach.setText("");
			txtSoLuong.setText("");
			txtGiaNhap.setText("");
			txtSoLuong.setText("");
			txtMoTa.setText("");
			txtNamXB.setText("");
			txtSoTrang.setText("");
			cbbLoaiSach.setSelectedIndex(0);
			cbbNCC.setSelectedIndex(0);
			cbbNhaXB.setSelectedIndex(0);
			cbbTacGia.setSelectedIndex(0);
			lbAnh.setIcon(ResizeImage(String.valueOf("img/macdinh.png")));
		}
	}
	private boolean validData() {
		String tenSach = txtTenSach.getText().trim();
		String namXB = txtNamXB.getText().trim();
		String soLuong = txtSoLuong.getText().trim();
		String soTrang = txtSoTrang.getText().trim();
		String giaNhap = txtGiaNhap.getText().trim();
		String moTa = txtMoTa.getText().trim();
		
		// Tựa sách không được để trống,
		// có thể gồm nhiều từ ngăn cách bởi khoảng trắng.
		// Không chứa ký số hoặc các ký tự đặc biệt khác
		if(!(tenSach.length()>0 && tenSach.matches("^[aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆ\n"
				+ "fFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTu\n"
				+ "UùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789 ]+"))) {
			JOptionPane.showMessageDialog(this, "Tên sách không được chứ các ký tự đặc biệt");
			txtTenSach.requestFocus();
			return false;
		}
		if (namXB.length() > 0) {
			try {
				int x = Integer.parseInt(namXB);
				int namHienTai = Calendar.getInstance().get(Calendar.YEAR);
				if (!(x >= 1900 && x <= namHienTai)) {
					JOptionPane.showMessageDialog(this, "Error : Năm xuất bản >= 1900 && <= " + namHienTai);
					txtNamXB.requestFocus();
					return false;
				}
			} catch (NumberFormatException ex) {
				JOptionPane.showMessageDialog(this, "Error ! Năm phải nhập số");
				txtNamXB.requestFocus();
				return false;
			}
		}
		if (soLuong.length() > 0) {
			try {
				int x = Integer.parseInt(soLuong);
				if (x <= 0) {
					JOptionPane.showMessageDialog(this, "Error! Số lượng phải là số nguyên dương");
					txtSoLuong.requestFocus();
					return false;
				}
			} catch (NumberFormatException ex) {
				JOptionPane.showMessageDialog(this, "Error! Số lượng phải nhập là số nguyên dương");
				txtSoLuong.requestFocus();
				return false;
			}
		}
		if(soTrang.length() > 0) {
			try {
				int x = Integer.parseInt(soTrang);
				if (x <= 0) {
					JOptionPane.showMessageDialog(this, "Error! Số trang phải là số nguyên dương");
					txtSoTrang.requestFocus();
					return false;
				}
			} catch (NumberFormatException ex) {
				JOptionPane.showMessageDialog(this, "Error! Số trang phải nhập là số nguyên dương");
				txtSoTrang.requestFocus();
				return false;
			}
		}
		if(giaNhap.length() > 0) {
			try {
				double y = Double.parseDouble(giaNhap);
				if (y < 0) {
					JOptionPane.showMessageDialog(this, "Error: Đơn giá phải > 0.");
					txtGiaNhap.requestFocus();
					return false;
				}
			} catch (NumberFormatException ex) {
				JOptionPane.showMessageDialog(this, "Error: Đơn giá phải nhập số.");
				txtGiaNhap.requestFocus();
				return false;
			}
		}
		if(!(moTa.length()>0)) {
			JOptionPane.showMessageDialog(this, "Error! Bạn chưa nhập mô tả");
			txtMoTa.requestFocus();
			return false;
		}
		
		return true;
	}
	public static ImageIcon ResizeImage(String valueOf) {
		ImageIcon myImage = new ImageIcon(valueOf);
		Image img = myImage.getImage();
		Image newImg = img.getScaledInstance(lbAnh.getWidth(), lbAnh.getHeight(), Image.SCALE_SMOOTH);
		ImageIcon image = new ImageIcon(newImg);
		return image;
	}

	public Dao_PhatSinhMa getDao_PhatSinhMa() {
		return dao_PhatSinhMa;
	}

	public void setDao_PhatSinhMa(Dao_PhatSinhMa dao_PhatSinhMa) {
		this.dao_PhatSinhMa = dao_PhatSinhMa;
	}

	public static Dao_SanPham getDao_SanPham() {
		return dao_SanPham;
	}

	public static void setDao_SanPham(Dao_SanPham dao_SanPham) {
		GUI_ThemSach.dao_SanPham = dao_SanPham;
	}

	public static Dao_LoaiSanPham getDao_LoaiSanPham() {
		return dao_LoaiSanPham;
	}

	public static void setDao_LoaiSanPham(Dao_LoaiSanPham dao_LoaiSanPham) {
		GUI_ThemSach.dao_LoaiSanPham = dao_LoaiSanPham;
	}

	public static Dao_TacGia getDao_TacGia() {
		return dao_TacGia;
	}

	public static void setDao_TacGia(Dao_TacGia dao_TacGia) {
		GUI_ThemSach.dao_TacGia = dao_TacGia;
	}

	public static Dao_NhaCungCap getDao_NhaCungCap() {
		return dao_NhaCungCap;
	}

	public static void setDao_NhaCungCap(Dao_NhaCungCap dao_NhaCungCap) {
		GUI_ThemSach.dao_NhaCungCap = dao_NhaCungCap;
	}

	public static Dao_NhaXuatBan getDao_NhaXuatBan() {
		return dao_NhaXuatBan;
	}

	public static void setDao_NhaXuatBan(Dao_NhaXuatBan dao_NhaXuatBan) {
		GUI_ThemSach.dao_NhaXuatBan = dao_NhaXuatBan;
	}

	public javax.swing.JButton getBtnChonAnh() {
		return btnChonAnh;
	}

	public void setBtnChonAnh(javax.swing.JButton btnChonAnh) {
		this.btnChonAnh = btnChonAnh;
	}

	public javax.swing.JButton getBtnHuy() {
		return btnHuy;
	}

	public void setBtnHuy(javax.swing.JButton btnHuy) {
		this.btnHuy = btnHuy;
	}

	public javax.swing.JButton getBtnLamMoi() {
		return btnLamMoi;
	}

	public void setBtnLamMoi(javax.swing.JButton btnLamMoi) {
		this.btnLamMoi = btnLamMoi;
	}

	public javax.swing.JButton getBtnXacNhan() {
		return btnXacNhan;
	}

	public void setBtnXacNhan(javax.swing.JButton btnXacNhan) {
		this.btnXacNhan = btnXacNhan;
	}

	public javax.swing.JComboBox<String> getCbbLoaiSach() {
		return cbbLoaiSach;
	}

	public void setCbbLoaiSach(javax.swing.JComboBox<String> cbbLoaiSach) {
		this.cbbLoaiSach = cbbLoaiSach;
	}

	public javax.swing.JComboBox<String> getCbbNCC() {
		return cbbNCC;
	}

	public void setCbbNCC(javax.swing.JComboBox<String> cbbNCC) {
		this.cbbNCC = cbbNCC;
	}

	public javax.swing.JComboBox<String> getCbbNhaXB() {
		return cbbNhaXB;
	}

	public void setCbbNhaXB(javax.swing.JComboBox<String> cbbNhaXB) {
		this.cbbNhaXB = cbbNhaXB;
	}

	public javax.swing.JComboBox<String> getCbbTacGia() {
		return cbbTacGia;
	}

	public void setCbbTacGia(javax.swing.JComboBox<String> cbbTacGia) {
		this.cbbTacGia = cbbTacGia;
	}

	public javax.swing.JLabel getjLabel21() {
		return jLabel21;
	}

	public void setjLabel21(javax.swing.JLabel jLabel21) {
		this.jLabel21 = jLabel21;
	}

	public javax.swing.JLabel getjLabel22() {
		return jLabel22;
	}

	public void setjLabel22(javax.swing.JLabel jLabel22) {
		this.jLabel22 = jLabel22;
	}

	public javax.swing.JLabel getjLabel23() {
		return jLabel23;
	}

	public void setjLabel23(javax.swing.JLabel jLabel23) {
		this.jLabel23 = jLabel23;
	}

	public javax.swing.JLabel getjLabel24() {
		return jLabel24;
	}

	public void setjLabel24(javax.swing.JLabel jLabel24) {
		this.jLabel24 = jLabel24;
	}

	public javax.swing.JLabel getjLabel25() {
		return jLabel25;
	}

	public void setjLabel25(javax.swing.JLabel jLabel25) {
		this.jLabel25 = jLabel25;
	}

	public javax.swing.JLabel getjLabel26() {
		return jLabel26;
	}

	public void setjLabel26(javax.swing.JLabel jLabel26) {
		this.jLabel26 = jLabel26;
	}

	public javax.swing.JLabel getjLabel27() {
		return jLabel27;
	}

	public void setjLabel27(javax.swing.JLabel jLabel27) {
		this.jLabel27 = jLabel27;
	}

	public javax.swing.JLabel getjLabel28() {
		return jLabel28;
	}

	public void setjLabel28(javax.swing.JLabel jLabel28) {
		this.jLabel28 = jLabel28;
	}

	public javax.swing.JLabel getjLabel29() {
		return jLabel29;
	}

	public void setjLabel29(javax.swing.JLabel jLabel29) {
		this.jLabel29 = jLabel29;
	}

	public javax.swing.JLabel getjLabel30() {
		return jLabel30;
	}

	public void setjLabel30(javax.swing.JLabel jLabel30) {
		this.jLabel30 = jLabel30;
	}

	public javax.swing.JLabel getjLabel31() {
		return jLabel31;
	}

	public void setjLabel31(javax.swing.JLabel jLabel31) {
		this.jLabel31 = jLabel31;
	}

	public javax.swing.JLabel getjLabel32() {
		return jLabel32;
	}

	public void setjLabel32(javax.swing.JLabel jLabel32) {
		this.jLabel32 = jLabel32;
	}

	public javax.swing.JLabel getjLabel33() {
		return jLabel33;
	}

	public void setjLabel33(javax.swing.JLabel jLabel33) {
		this.jLabel33 = jLabel33;
	}

	public javax.swing.JPanel getjPanel3() {
		return jPanel3;
	}

	public void setjPanel3(javax.swing.JPanel jPanel3) {
		this.jPanel3 = jPanel3;
	}

	public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public static javax.swing.JLabel getLbAnh() {
		return lbAnh;
	}

	public static void setLbAnh(javax.swing.JLabel lbAnh) {
		GUI_ThemSach.lbAnh = lbAnh;
	}

	public javax.swing.JLabel getLbMa() {
		return lbMa;
	}

	public void setLbMa(javax.swing.JLabel lbMa) {
		this.lbMa = lbMa;
	}

	public javax.swing.JTextField getTxtGiaNhap() {
		return txtGiaNhap;
	}

	public void setTxtGiaNhap(javax.swing.JTextField txtGiaNhap) {
		this.txtGiaNhap = txtGiaNhap;
	}

	public javax.swing.JTextArea getTxtMoTa() {
		return txtMoTa;
	}

	public void setTxtMoTa(javax.swing.JTextArea txtMoTa) {
		this.txtMoTa = txtMoTa;
	}

	public javax.swing.JTextField getTxtNamXB() {
		return txtNamXB;
	}

	public void setTxtNamXB(javax.swing.JTextField txtNamXB) {
		this.txtNamXB = txtNamXB;
	}

	public javax.swing.JTextField getTxtSoLuong() {
		return txtSoLuong;
	}

	public void setTxtSoLuong(javax.swing.JTextField txtSoLuong) {
		this.txtSoLuong = txtSoLuong;
	}

	public javax.swing.JTextField getTxtSoTrang() {
		return txtSoTrang;
	}

	public void setTxtSoTrang(javax.swing.JTextField txtSoTrang) {
		this.txtSoTrang = txtSoTrang;
	}

	public javax.swing.JTextField getTxtTenSach() {
		return txtTenSach;
	}

	public void setTxtTenSach(javax.swing.JTextField txtTenSach) {
		this.txtTenSach = txtTenSach;
	}

	public String getDuongDanAnh() {
		return duongDanAnh;
	}

	public void setDuongDanAnh(String duongDanAnh) {
		this.duongDanAnh = duongDanAnh;
	}
	
}
