/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.Dao_LoaiSanPham;
import dao.Dao_NhaCungCap;
import dao.Dao_NhaXuatBan;
import dao.Dao_SanPham;
import dao.Dao_TacGia;
import entity.LoaiSanPham;
import entity.NhaCungCap;
import entity.NhaXuatBan;
import entity.SanPham;
import entity.TacGia;
import gui.GUI_LapHD.RightClickPopUp;

/**
 *
 * @author TuanPC
 */
public class GUI_Sach extends javax.swing.JPanel implements ActionListener{
	private static Dao_SanPham dao_SanPham= new Dao_SanPham();
	private static Dao_LoaiSanPham dao_LoaiSanPham = new Dao_LoaiSanPham();
	private static Dao_TacGia dao_TacGia = new Dao_TacGia();
	private static Dao_NhaCungCap dao_NhaCungCap = new Dao_NhaCungCap();
	private static Dao_NhaXuatBan dao_NhaXuatBan = new Dao_NhaXuatBan();
	private static DefaultTableModel model;
	public static int edit = 0;
    /**
     * Creates new form GUI_Sach
     */
    public GUI_Sach() {
    	try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	 initComponents();
         loadCbo();
         updateTable();
         btnThem.addActionListener(this);
         btnXoa.addActionListener(this);
         btnSua.addActionListener(this);
         btnLamMoi.addActionListener(this);
         btnTim.addActionListener(this);
         table.addMouseListener(new MouseListener() {
 			
 			@Override
 			public void mouseReleased(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mousePressed(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mouseExited(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mouseEntered(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mouseClicked(MouseEvent e) {
 				if(SwingUtilities.isRightMouseButton(e)) {
 					int r = table.rowAtPoint(e.getPoint());
 					if (r >= 0 && r < table.getRowCount()) {
 						table.setRowSelectionInterval(r, r);
 					} else {
 						table.clearSelection();
 					}
 					int rowselect = table.getSelectedRow();
 					if (rowselect < 0)
 						return;
 					else {
 						popSP.show(e.getComponent(),e.getX(),e.getY());
 					}
 				}
 			}
 		});
    }
    private void loadCbo() {
		ArrayList<LoaiSanPham> dataList = dao_LoaiSanPham.getLoaiSach();
		for(LoaiSanPham loaisp : dataList) {
			cbbLoaiSach.addItem(loaisp.getChiTiet());
		}
		ArrayList<NhaCungCap> listNCC = dao_NhaCungCap.getAllNCC();
		for (NhaCungCap nhaCungCap : listNCC) {
			cbbNCC.addItem(nhaCungCap.getTenNCC());
		}
		ArrayList<TacGia> listTG = dao_TacGia.getAllTG();
		for (TacGia tacGia : listTG) {
			cbbTacGia.addItem(tacGia.getHoTen());
		}
		ArrayList<NhaXuatBan> listNXB = dao_NhaXuatBan.getAllNXB();
		for (NhaXuatBan nhaXuatBan : listNXB) {
			cbbNXB.addItem(nhaXuatBan.getTenNXB());
		}
		
		
	}
	
	
	public static void updateTable() {
		model.setRowCount(0);
		for (SanPham sach : dao_SanPham.getListSach()) {
			String nxb = dao_NhaXuatBan.getTenNXBTheoMa(sach.getNhaXB().getMaNXB());
			String tg = dao_TacGia.getTenTGTheoMa(sach.getTacGia().getMaTG());
			String ncc = dao_NhaCungCap.getTenNCCTheoMa(sach.getNhaCungCap().getMaNCC());
			String loai = dao_LoaiSanPham.getChiTietTheoMaLoai(sach.getLoaiSP().getMaLoai());
			Object row[] = {sach.getMaSanPham(),sach.getTenSanPham(),sach.getSoLuong(),sach.getGiaNhap(),
					sach.getNamXB(),sach.getSoTrang(),nxb,tg,ncc,sach.getMoTa(),loai};
			model.addRow(row);
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        txtNamXB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbNXB = new javax.swing.JComboBox<>();
        chkTenSach = new javax.swing.JCheckBox();
        chkNamXB = new javax.swing.JCheckBox();
        btnTim = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        cbbLoaiSach = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbTacGia = new javax.swing.JComboBox<>();
        cbbNCC = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1426, 722));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Sách");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên Sách:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Năm Xuất Bản:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Loại Sách:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Nhà Xuất Bản:");

        cbbNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        btnTim.setBackground(new java.awt.Color(51, 153, 255));
        btnTim.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon("img\\timkiem24.png")); // NOI18N
        btnTim.setText("Tìm Kiếm");

        btnLamMoi.setBackground(new java.awt.Color(51, 153, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\refresh24.png")); // NOI18N
        btnLamMoi.setText("Làm mới");

        cbbLoaiSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tác Giả:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Nhà Cung Cấp:");

        cbbTacGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        cbbNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txtTenSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTenSach, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkNamXB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbLoaiSach, 0, 312, Short.MAX_VALUE)
                    .addComponent(cbbNXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbbLoaiSach)
                            .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(chkNamXB))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cbbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkTenSach))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbbTacGia)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbbNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách sách"));

        table.setModel(model=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng ", "Giá Nhập", "Năm Xuất Bản", "Số Trang", "Nhà Xuất Bản", "Tác Giả", "Nhà Cung Cấp", "Mô Tả", "Loại Sách"
            }
        ));
        table.setRowHeight(30);
        table.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        btnThem.setBackground(new java.awt.Color(51, 153, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon("img\\add.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 153, 255));
        btnSua.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon("img\\fix.png")); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 153, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon("img\\delete.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(btnThem)
                .addGap(57, 57, 57)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 530, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1426, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbLoaiSach;
    private javax.swing.JComboBox<String> cbbNCC;
    private javax.swing.JComboBox<String> cbbNXB;
    private javax.swing.JComboBox<String> cbbTacGia;
    private javax.swing.JCheckBox chkNamXB;
    private javax.swing.JCheckBox chkTenSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable table;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if(o.equals(btnThem)) {
                    GUI_ThemSach gui_ThemSach = new GUI_ThemSach();
                    gui_ThemSach.setVisible(true);
                    gui_ThemSach.setLocationRelativeTo(null);
                    gui_ThemSach.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    edit = 1;
		}else if(o.equals(btnXoa)) {
			if(table.getSelectedRow()!=-1) {
				if(JOptionPane.showConfirmDialog(this, "Có chắc chắn xóa không","Cảnh báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
					dao_SanPham.xoaSach(model.getValueAt(table.getSelectedRow(), 0).toString());
					model.removeRow(table.getSelectedRow());
					JOptionPane.showMessageDialog(this, "Xóa thành công");
				}
			}else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn sách cần xóa");
			}
		}else if(o.equals(btnSua)) {
			int row = table.getSelectedRow();
			if(row!=-1) {
				GUI_ThemSach gui_ThemSach = new GUI_ThemSach();
				gui_ThemSach.setVisible(true);
				gui_ThemSach.setLocationRelativeTo(null);
				gui_ThemSach.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
				gui_ThemSach.getLbMa().setText(model.getValueAt(row, 0).toString());
				gui_ThemSach.getTxtTenSach().setText(model.getValueAt(row, 1).toString());
				gui_ThemSach.getTxtSoLuong().setText(model.getValueAt(row, 2).toString());
				gui_ThemSach.getTxtGiaNhap().setText(model.getValueAt(row, 3).toString());
				gui_ThemSach.getTxtNamXB().setText(model.getValueAt(row, 4).toString());
				gui_ThemSach.getTxtSoTrang().setText(model.getValueAt(row, 5).toString());
				gui_ThemSach.getCbbNhaXB().setSelectedItem(model.getValueAt(row, 6).toString());
				gui_ThemSach.getCbbTacGia().setSelectedItem(model.getValueAt(row, 7).toString());
				gui_ThemSach.getCbbNCC().setSelectedItem(model.getValueAt(row, 8).toString());
				gui_ThemSach.getTxtMoTa().setText(model.getValueAt(row, 9).toString());
				gui_ThemSach.getCbbLoaiSach().setSelectedItem(model.getValueAt(row, 10).toString());
				GUI_ThemSach.getLbAnh().setIcon(GUI_ThemSach.ResizeImage(String.valueOf(dao_SanPham.gethinhAnhTheoMa(model.getValueAt(row, 0).toString()))));
				edit=2;
			}else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn sách cần sửa");
			}
			
		}else if(o.equals(btnTim)) {
			String tenSP = "%"+txtTenSach.getText().trim()+"%";
			String namXB = "%"+txtNamXB.getText().trim()+"%";
			String l = dao_LoaiSanPham.getMaLoaiTheoChiTiet(cbbLoaiSach.getSelectedItem().toString());
			String nhaXB = dao_NhaXuatBan.getMaNXBTheoTen(cbbNXB.getSelectedItem().toString());
			String t = dao_TacGia.getMaTheoTen(cbbTacGia.getSelectedItem().toString());
			String n = dao_NhaCungCap.getMaNCCTheoTen(cbbNCC.getSelectedItem().toString());
			
			if(cbbLoaiSach.getSelectedIndex()==0) {
				l = "";
			}
			if(cbbNCC.getSelectedIndex()==0) {
				n = "";
			}
			if(cbbNXB.getSelectedIndex()==0) {
				nhaXB = "";
			}
			if(cbbTacGia.getSelectedIndex()==0) {
				t = "";
			}
			if(chkTenSach.isSelected())
				tenSP = txtTenSach.getText().trim();
			if(chkNamXB.isSelected())
				namXB = txtNamXB.getText().trim();
			if(txtTenSach.getText().trim().equals(""))
				tenSP = "%%";
			if(txtNamXB.getText().trim().equals(""))
				namXB = "%%";
			model.setRowCount(0);
			for (SanPham sach : dao_SanPham.getSachTheoDK(tenSP, namXB, l, nhaXB, t, n)) {
				String nxb = dao_NhaXuatBan.getTenNXBTheoMa(sach.getNhaXB().getMaNXB());
				String tg = dao_TacGia.getTenTGTheoMa(sach.getTacGia().getMaTG());
				String ncc = dao_NhaCungCap.getTenNCCTheoMa(sach.getNhaCungCap().getMaNCC());
				String loai = dao_LoaiSanPham.getChiTietTheoMaLoai(sach.getLoaiSP().getMaLoai());
				Object row[] = {sach.getMaSanPham(),sach.getTenSanPham(),sach.getSoLuong(),sach.getGiaNhap(),
						sach.getNamXB(),sach.getSoTrang(),nxb,tg,ncc,sach.getMoTa(),loai};
				model.addRow(row);
			}
		}else if(o.equals(btnLamMoi)) {
			txtNamXB.setText("");
			txtTenSach.setText("");
			chkNamXB.setSelected(false);
			chkTenSach.setSelected(false);
			cbbLoaiSach.setSelectedIndex(0);
			cbbNCC.setSelectedIndex(0);
			cbbNXB.setSelectedIndex(0);
			cbbTacGia.setSelectedIndex(0);
			updateTable();
		}
	}
	
	public static javax.swing.JTable getTable() {
		return table;
	}
	public void setTable(javax.swing.JTable table) {
		this.table = table;
	}

	public class RightClickPopUp extends JPopupMenu {
		public RightClickPopUp(JTable table) {

			JMenuItem themGG = new JMenuItem("Thêm giảm giá");

			themGG.addActionListener(new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {
					GUI_GiamGia gui_GiamGia = new GUI_GiamGia();
					gui_GiamGia.setVisible(true);
					gui_GiamGia.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
					gui_GiamGia.setLocationRelativeTo(null);
				}
				
			});
			add(themGG);
		}
	}

	private RightClickPopUp popSP = new RightClickPopUp(table);
}
