/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.Dao_DiaChi;
import dao.Dao_NhaCungCap;
import dao.Dao_SanPham;
import entity.DiaChi;
import entity.KhachHang;
import entity.NhaCungCap;

/**
 *
 * @author TuanPC
 */
public class GUI_NhaCungCap extends javax.swing.JPanel implements ActionListener {
	public static int edit = 0;
	private Dao_DiaChi daoDiaChi;
	private Vector<String> dsTinhTP;
	public static Dao_NhaCungCap daoNCC;
	public static DefaultTableModel modelNCC;
	private Dao_SanPham dao_SanPham = new Dao_SanPham();

	/**
	 * Creates new form GUI_NhaCungCap
	 */
	public GUI_NhaCungCap() {
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException ex) {
		}
		daoNCC = new Dao_NhaCungCap();
		daoDiaChi = new Dao_DiaChi();
		initComponents();
		updateTable();
		cbbTinhTP.addActionListener(this);
		btnThem.addActionListener(this);
		btnXoa.addActionListener(this);
		btnSua.addActionListener(this);
		btnLamMoi.addActionListener(this);
		btnTim.addActionListener(this);
		for (String dc : daoDiaChi.getAllTinh()) {
			cbbTinhTP.addItem(dc);
		}
	}

	public static void updateTable() {
		modelNCC.setRowCount(0);
		ArrayList<NhaCungCap> listNCC = daoNCC.getAllNCC();
		for (NhaCungCap ncc : listNCC) {
			modelNCC.addRow(new Object[] { ncc.getMaNCC(), ncc.getTenNCC(), ncc.getSdt(), ncc.getDiaChi().getPhuongXa(),
					ncc.getDiaChi().getQuanHuyen(), ncc.getDiaChi().getTinhTP() });
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		txtMaNCC = new javax.swing.JTextField();
		txtSDT = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		txtTenNCC = new javax.swing.JTextField();
		cbbTinhTP = new javax.swing.JComboBox<>();
		chkMaNCC = new javax.swing.JCheckBox();
		chkSDT = new javax.swing.JCheckBox();
		chkTenNCC = new javax.swing.JCheckBox();
		btnTim = new javax.swing.JButton();
		btnLamMoi = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		btnThem = new javax.swing.JButton();
		btnSua = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setPreferredSize(new java.awt.Dimension(1426, 722));

		jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Quản Lý Nhà Cung Cấp");

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
				"Tìm kiếm"));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel2.setText("Mã NCC:");

		jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel6.setText("Số điện thoại: ");

		jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel7.setText("Tên NCC:");

		jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel8.setText("Khu Vực:");

		cbbTinhTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

		btnTim.setBackground(new java.awt.Color(51, 153, 255));
		btnTim.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(new javax.swing.ImageIcon(
				"img\\timkiem24.png")); // NOI18N
		btnTim.setText("Tìm Kiếm");

		btnLamMoi.setBackground(new java.awt.Color(51, 153, 255));
		btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
		btnLamMoi.setIcon(new javax.swing.ImageIcon(
				"img\\refresh24.png")); // NOI18N
		btnLamMoi.setText("Làm mới");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 408,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(chkSDT))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 408,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(chkMaNCC)))
						.addGap(95, 95, 95)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 408,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 408,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(chkTenNCC)
						.addGap(57, 57, 57)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 41, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
												.addComponent(chkMaNCC)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtSDT)
										.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(8, 8, 8)
												.addComponent(chkSDT))))
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtTenNCC)
										.addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(10, 10, 10)
												.addComponent(chkTenNCC))
										.addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12,
										Short.MAX_VALUE)
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35,
												Short.MAX_VALUE)
										.addComponent(cbbTinhTP).addComponent(btnLamMoi,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
				"Danh sách nhà cung cấp"));

		table.setModel(modelNCC = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số điện thoại", "Phường/Xã", "Quận/Huyện",
				"Tỉnh/Thành Phố" }));
		table.setRowHeight(30);
		table.setSelectionBackground(new java.awt.Color(51, 153, 255));
		jScrollPane1.setViewportView(table);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE));

		btnThem.setBackground(new java.awt.Color(51, 153, 255));
		btnThem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnThem.setForeground(new java.awt.Color(255, 255, 255));
		btnThem.setIcon(new javax.swing.ImageIcon(
				"img\\add.png")); // NOI18N
		btnThem.setText("Thêm");
		btnThem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThemActionPerformed(evt);
			}
		});

		btnSua.setBackground(new java.awt.Color(51, 153, 255));
		btnSua.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnSua.setForeground(new java.awt.Color(255, 255, 255));
		btnSua.setIcon(new javax.swing.ImageIcon(
				"img\\fix.png")); // NOI18N
		btnSua.setText("Sửa");
		btnSua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSuaActionPerformed(evt);
			}
		});

		btnXoa.setBackground(new java.awt.Color(51, 153, 255));
		btnXoa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnXoa.setForeground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(new javax.swing.ImageIcon(
				"img\\delete.png")); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXoaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(487, 487, 487)
										.addComponent(btnThem).addGap(57, 57, 57)
										.addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(53, 53, 53)
										.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(23, 530, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel3,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 1426, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 722, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
	}// </editor-fold>//GEN-END:initComponents

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnThemActionPerformed

	private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSuaActionPerformed

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnXoaActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLamMoi;
	private javax.swing.JButton btnSua;
	private javax.swing.JButton btnThem;
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnXoa;
	private javax.swing.JComboBox<String> cbbTinhTP;
	private javax.swing.JCheckBox chkMaNCC;
	private javax.swing.JCheckBox chkSDT;
	private javax.swing.JCheckBox chkTenNCC;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable table;
	private javax.swing.JTextField txtMaNCC;
	private javax.swing.JTextField txtSDT;
	private javax.swing.JTextField txtTenNCC;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if (o.equals(btnThem)) {
			GUI_ThemNhaCungCap gui_ThemNCC = new GUI_ThemNhaCungCap();
			gui_ThemNCC.setVisible(true);
			gui_ThemNCC.setLocationRelativeTo(null);
			gui_ThemNCC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			edit = 1;
		} else if (o.equals(btnXoa)) {
			if(dao_SanPham.getSPTheoMaNCC(modelNCC.getValueAt(table.getSelectedRow(), 0).toString()).size()>0) {
				JOptionPane.showMessageDialog(this, "Hãy xóa sản phẩm liên quan trước");
			}else {
				if (table.getSelectedRow() != -1) {
					if (JOptionPane.showConfirmDialog(this, "Có chắc chắn xóa không?", "Cảnh báo",
							JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
						daoNCC.xoaNCC(modelNCC.getValueAt(table.getSelectedRow(), 0).toString());
						modelNCC.removeRow(table.getSelectedRow());
						JOptionPane.showMessageDialog(this, "Xóa thành công");
					}
				} else {
					JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhà cung cấp cần xóa");
				}
			}
		} else if (o.equals(btnLamMoi)) {
			txtMaNCC.setText("");
			txtTenNCC.setText("");
			txtSDT.setText("");
			cbbTinhTP.setSelectedIndex(0);
			updateTable();
		} else if (o.equals(btnSua)) {
			int row = table.getSelectedRow();
			if (row != -1) {
				GUI_ThemNhaCungCap guiSuaNCC = new GUI_ThemNhaCungCap();
				guiSuaNCC.setVisible(true);
				guiSuaNCC.setLocationRelativeTo(null);
				guiSuaNCC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
				guiSuaNCC.getLbMaNCC().setText(modelNCC.getValueAt(row, 0).toString());
				guiSuaNCC.getTxtTenNCC().setText(modelNCC.getValueAt(row, 1).toString());
				guiSuaNCC.getTxtSDT().setText(modelNCC.getValueAt(row, 2).toString());
				guiSuaNCC.getCbbTinhTP().setSelectedItem(modelNCC.getValueAt(row, 5).toString());
				guiSuaNCC.getCbbQuanHuyen().setSelectedItem(modelNCC.getValueAt(row, 4).toString());
				guiSuaNCC.getCbbPhuongXa().setSelectedItem(modelNCC.getValueAt(row, 3).toString());

				edit = 2;
			} else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhà cung cấp cần sửa");
			}

		} else if (o.equals(btnTim)) {
			if (txtMaNCC.getText().equals("") && txtTenNCC.getText().equals("") && txtSDT.getText().equals("")
					&& cbbTinhTP.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(this, "Nhập thông tin bạn muốn tìm");
			} else {
				String ma = "%" + txtMaNCC.getText().trim() + "%";
				String sd = "%" + txtSDT.getText().trim() + "%";
				String ten = "%" + txtTenNCC.getText().trim() + "%";
				String gt = cbbTinhTP.getSelectedItem().toString();
				if (cbbTinhTP.getSelectedIndex() == 0) {
					gt = "";
				}
				if (chkMaNCC.isSelected())
					ma = txtMaNCC.getText().trim();
				if (chkTenNCC.isSelected())
					ten = txtTenNCC.getText().trim();
				if (chkSDT.isSelected())
					sd = txtSDT.getText().trim();
				if (txtMaNCC.getText().trim().equals(""))
					ma = "%%";
				if (txtTenNCC.getText().trim().equals(""))
					ten = "%%";
				if (txtSDT.getText().trim().equals(""))
					sd = "%%";
				modelNCC.setRowCount(0);
				ArrayList<NhaCungCap> listNCC = daoNCC.getNCCTheoDK(ma, ten, sd, gt);
				for (NhaCungCap ncc : listNCC) {
					modelNCC.addRow(
							new Object[] { ncc.getMaNCC(), ncc.getTenNCC(), ncc.getSdt(), ncc.getDiaChi().getPhuongXa(),
									ncc.getDiaChi().getQuanHuyen(), ncc.getDiaChi().getTinhTP() });
				}
			}
		}
	}
}
