/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.Dao_KhachHang;
import dao.Dao_LoaiSanPham;
import dao.Dao_SanPham;
import dao.Dao_XuatXu;
import entity.KhachHang;
import entity.LoaiSanPham;
import entity.NhanVien;
import entity.SanPham;
import entity.XuatXu;
import gui.GUI_Sach.RightClickPopUp;

/**
 *
 * @author TuanPC
 */
public class GUI_VanPhongPham extends javax.swing.JPanel implements ActionListener{
	private static Dao_SanPham dao_SanPham;
	private static Dao_LoaiSanPham dao_LoaiSanPham = new Dao_LoaiSanPham();
	private static Dao_XuatXu dao_XuatXu = new Dao_XuatXu();
	public static int edit = 0;
    /**
     * Creates new form GUI_VanPhongPham
     */
    public GUI_VanPhongPham() {
    	initComponents();
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException ex) {
        }    
            initComponents();
            dao_SanPham = new Dao_SanPham();
            updataTable();
            btnThem.addActionListener(this);
            btnXoa.addActionListener(this);
            btnSua.addActionListener(this);
            btnTim.addActionListener(this);
            btnLamMoi.addActionListener(this);
        for (XuatXu xuatXu : dao_XuatXu.getAllXuatXu()) {
        	cbbXuatXu.addItem(xuatXu.getTenNuocXX());
        }
        for (String loai : dao_LoaiSanPham.getAllChiTietVPP()) {
			cbbTenLoai.addItem(loai);
		}
        tableVPP.addMouseListener(new MouseListener() {
 			
 			@Override
 			public void mouseReleased(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mousePressed(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mouseExited(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mouseEntered(MouseEvent e) {
 				// TODO Auto-generated method stub
 				
 			}
 			
 			@Override
 			public void mouseClicked(MouseEvent e) {
 				if(SwingUtilities.isRightMouseButton(e)) {
 					int r = tableVPP.rowAtPoint(e.getPoint());
 					if (r >= 0 && r < tableVPP.getRowCount()) {
 						tableVPP.setRowSelectionInterval(r, r);
 					} else {
 						tableVPP.clearSelection();
 					}
 					int rowselect = tableVPP.getSelectedRow();
 					if (rowselect < 0)
 						return;
 					else {
 						popSP.show(e.getComponent(),e.getX(),e.getY());
 					}
 				}
 			}
 		});
    }
    public static void updataTable() {
    	modelVPP.setRowCount(0);
		for (SanPham sp : dao_SanPham.getAllVPP()) {
			String loai = dao_LoaiSanPham.getChiTietTheoMaLoai(sp.getLoaiSP().getMaLoai());
			String xx = dao_XuatXu.getXuatXuTheoMaXX(sp.getXuatXu().getMaXX());
			Object row [] = {sp.getMaSanPham(),sp.getTenSanPham(),sp.getSoLuong(),sp.getGiaNhap(),sp.getThuongHieu(),loai,xx};
			modelVPP.addRow(row);
		}
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimTenSP = new javax.swing.JTextField();
        txtTimThuongHieu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbXuatXu = new javax.swing.JComboBox<>();
        chkTimHoTen = new javax.swing.JCheckBox();
        chkTimSDT = new javax.swing.JCheckBox();
        btnTim = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        cbbTenLoai = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVPP = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1426, 722));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Văn Phòng Phẩm");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm kiếm"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tìm tên sản phẩm:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Thương Hiệu:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tìm tên loại:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tìm nước xuất xứ:");

        cbbXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        btnTim.setBackground(new java.awt.Color(51, 153, 255));
        btnTim.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon("img\\timkiem24.png")); // NOI18N
        btnTim.setText("Tìm Kiếm");

        btnLamMoi.setBackground(new java.awt.Color(51, 153, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\refresh24.png")); // NOI18N
        btnLamMoi.setText("Làm mới");

        cbbTenLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkTimSDT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkTimHoTen)))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTimTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkTimHoTen)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTimThuongHieu)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(chkTimSDT))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbTenLoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(cbbXuatXu)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách văn phòng phẩm"));

        tableVPP.setModel(modelVPP = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng ", "Giá Nhập", "Thương Hiệu", "Tên Loại", "Xuất Xứ "
            }
        ));
        tableVPP.setRowHeight(30);
        tableVPP.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(tableVPP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        btnThem.setBackground(new java.awt.Color(51, 153, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon("img\\add.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 153, 255));
        btnSua.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon("img\\fix.png")); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 153, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon("img\\delete.png")); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(btnThem)
                .addGap(57, 57, 57)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 530, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1426, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTenLoai;
    private javax.swing.JComboBox<String> cbbXuatXu;
    private javax.swing.JCheckBox chkTimHoTen;
    private javax.swing.JCheckBox chkTimSDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tableVPP;
    private javax.swing.JTextField txtTimTenSP;
    private javax.swing.JTextField txtTimThuongHieu;
    private static DefaultTableModel modelVPP;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if(o.equals(btnThem)) {
                    GUI_ThemVanPhongPham gui_ThemVanPhongPham = new GUI_ThemVanPhongPham();
                    gui_ThemVanPhongPham.setVisible(true);
                    gui_ThemVanPhongPham.setLocationRelativeTo(null);
                    gui_ThemVanPhongPham.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    edit = 1;
		}else if(o.equals(btnXoa)) {
			if(tableVPP.getSelectedRow()!=-1) {
				if(JOptionPane.showConfirmDialog(this, "Có chắc chắn xóa không","Cảnh báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
					dao_SanPham.xoaVPP(modelVPP.getValueAt(tableVPP.getSelectedRow(), 0).toString());
					modelVPP.removeRow(tableVPP.getSelectedRow());
					JOptionPane.showMessageDialog(this, "Xóa thành công");
				}
			}else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn khách hàng cần xóa");
			}
		}else if(o.equals(btnSua)) {
			int row = tableVPP.getSelectedRow();
			if(row!=-1) {
				GUI_ThemVanPhongPham gui_ThemVanPhongPham = new GUI_ThemVanPhongPham();
				gui_ThemVanPhongPham.setVisible(true);
				gui_ThemVanPhongPham.setLocationRelativeTo(null);
				gui_ThemVanPhongPham.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
				gui_ThemVanPhongPham.getLbMaSP().setText(modelVPP.getValueAt(row, 0).toString());
				gui_ThemVanPhongPham.getTxtTenSP().setText(modelVPP.getValueAt(row, 1).toString());
				gui_ThemVanPhongPham.getTxtSoLuong().setText(modelVPP.getValueAt(row, 2).toString());
				gui_ThemVanPhongPham.getTxtGiaNhap().setText(modelVPP.getValueAt(row, 3).toString());
				gui_ThemVanPhongPham.getTxtThuongHieu().setText(modelVPP.getValueAt(row, 4).toString());
				gui_ThemVanPhongPham.getCbbLoaiSP().setSelectedItem(modelVPP.getValueAt(row, 5).toString());
				gui_ThemVanPhongPham.getCbbXuatXu().setSelectedItem(modelVPP.getValueAt(row, 6).toString());
				gui_ThemVanPhongPham.getLbAnh().setIcon(GUI_ThemVanPhongPham.ResizeImage(String.valueOf(dao_SanPham.gethinhAnhTheoMa(modelVPP.getValueAt(row, 0).toString()))));
				edit=2;
			}else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn khách hàng cần sửa");
			}
			
		}else if(o.equals(btnTim)) {
			String tenSP = "%"+txtTimTenSP.getText().trim()+"%";
			String th = "%"+txtTimThuongHieu.getText().trim()+"%";
			String x = dao_XuatXu.getMaXXTheoXX(cbbXuatXu.getSelectedItem().toString()); 
			String l = dao_LoaiSanPham.getMaLoaiTheoChiTiet(cbbTenLoai.getSelectedItem().toString()); 
			if(cbbXuatXu.getSelectedIndex()==0) {
				x = "";
			}
			if(cbbTenLoai.getSelectedIndex()==0) {
				l = "";
			}
			if(chkTimHoTen.isSelected())
				tenSP = txtTimTenSP.getText().trim();
			if(chkTimSDT.isSelected())
				th = txtTimThuongHieu.getText().trim();
			if(txtTimTenSP.getText().trim().equals(""))
				tenSP = "%%";
			if(txtTimThuongHieu.getText().trim().equals(""))
				th = "%%";
			modelVPP.setRowCount(0);
			for (SanPham sp : dao_SanPham.getVPPTheoDK(tenSP,th,x,l)) {
				String loai = dao_LoaiSanPham.getChiTietTheoMaLoai(sp.getLoaiSP().getMaLoai());
				String xx = dao_XuatXu.getXuatXuTheoMaXX(sp.getXuatXu().getMaXX());
				Object row [] = {sp.getMaSanPham(),sp.getTenSanPham(),sp.getSoLuong(),sp.getGiaNhap(),sp.getThuongHieu(),loai,xx};
				modelVPP.addRow(row);
			}
		}else if(o.equals(btnLamMoi)) {
			txtTimTenSP.setText("");
			txtTimThuongHieu.setText("");
			chkTimHoTen.setSelected(false);
			chkTimSDT.setSelected(false);
			cbbTenLoai.setSelectedIndex(0);
			cbbXuatXu.setSelectedIndex(0);
			updataTable();
		}
	}
	public static javax.swing.JTable getTable() {
		return tableVPP;
	}
	public void setTable(javax.swing.JTable tableVPP) {
		this.tableVPP = tableVPP;
	}

	public class RightClickPopUp extends JPopupMenu {
		public RightClickPopUp(JTable table) {

			JMenuItem themGG = new JMenuItem("Thêm giảm giá");

			themGG.addActionListener(new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {
					GUI_GiamGiaVPP gui_GiamGia = new GUI_GiamGiaVPP();
					gui_GiamGia.setVisible(true);
					gui_GiamGia.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
					gui_GiamGia.setLocationRelativeTo(null);
				}
				
			});
			add(themGG);
		}
	}

	private RightClickPopUp popSP = new RightClickPopUp(tableVPP);
}
