/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.Dao_LoaiSanPham;
import entity.LoaiSanPham;
import entity.NhanVien;

/**
 *
 * @author TuanPC
 */
public class GUI_LoaiSanPham extends javax.swing.JPanel implements ActionListener {
	public static int edit = 0;
	public static Dao_LoaiSanPham daoLoaiSP;
	public static DefaultTableModel modelLoaiSP;

	/**
	 * Creates new form GUI_LoaiSanPham
	 */
	public GUI_LoaiSanPham() {
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException ex) {

		}
		setBackground(Color.WHITE);
		daoLoaiSP = new Dao_LoaiSanPham();
		initComponents();
		updateTable();
		btnThem.addActionListener(this);
		btnXoa.addActionListener(this);
		btnSua.addActionListener(this);
		btnLamMoi.addActionListener(this);
		btnTim.addActionListener(this);
		for (String t : daoLoaiSP.getAllLoaiSP()) {
			cbbTenLoai.addItem(t);
		}
		cbbTenLoai.addActionListener(this);
	}

	public static void updateTable() {
		modelLoaiSP.setRowCount(0);
		ArrayList<LoaiSanPham> listLoaiSP = daoLoaiSP.getAllloaiSP();
		for (LoaiSanPham lsp : listLoaiSP) {
			modelLoaiSP.addRow(new Object[] { lsp.getMaLoai(), lsp.getTenLoai(), lsp.getChiTiet() });
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		txtMaLoai = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		cbbTenLoai = new javax.swing.JComboBox<>();
		chkMaLoai = new javax.swing.JCheckBox();
		btnTim = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		cbbChiTiet = new javax.swing.JComboBox<>();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		btnThem = new javax.swing.JButton();
		btnSua = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		btnLamMoi = new javax.swing.JButton();

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setPreferredSize(new java.awt.Dimension(1426, 722));

		jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Quản Lý Loại Sản Phẩm");

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
				"Tìm kiếm"));

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel2.setText("Mã Loại:");

		jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel8.setText("Tên Loại:");

		cbbTenLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

		btnTim.setBackground(new java.awt.Color(51, 153, 255));
		btnTim.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(new javax.swing.ImageIcon(
				"img\\timkiem24.png")); // NOI18N
		btnTim.setText("Tìm Kiếm");

		jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel9.setText("Chi Tiết:");

		cbbChiTiet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(66, 66, 66).addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(txtMaLoai)
										.addComponent(cbbTenLoai, javax.swing.GroupLayout.Alignment.LEADING, 0, 306,
												Short.MAX_VALUE)
										.addComponent(cbbChiTiet, javax.swing.GroupLayout.Alignment.LEADING, 0,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(chkMaLoai))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(126, 126, 126).addComponent(btnTim,
								javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(58, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18))
								.addGroup(
										jPanel2Layout.createSequentialGroup().addGap(39, 39, 39).addComponent(chkMaLoai)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26,
														Short.MAX_VALUE)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cbbTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(27, 27, 27)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cbbChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(43, 43, 43).addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
				"Danh sách nhà cung cấp"));

		table.setModel(modelLoaiSP = new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã Loại", "Tên Loại", "Chi Tiết" }));
		table.setRowHeight(30);
		table.setSelectionBackground(new java.awt.Color(51, 153, 255));
		jScrollPane1.setViewportView(table);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1));

		btnThem.setBackground(new java.awt.Color(51, 153, 255));
		btnThem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnThem.setForeground(new java.awt.Color(255, 255, 255));
		btnThem.setIcon(new javax.swing.ImageIcon(
				"img\\add.png")); // NOI18N
		btnThem.setText("Thêm");
		btnThem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThemActionPerformed(evt);
			}
		});

		btnSua.setBackground(new java.awt.Color(51, 153, 255));
		btnSua.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnSua.setForeground(new java.awt.Color(255, 255, 255));
		btnSua.setIcon(new javax.swing.ImageIcon(
				"img\\fix.png")); // NOI18N
		btnSua.setText("Sửa");
		btnSua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSuaActionPerformed(evt);
			}
		});

		btnXoa.setBackground(new java.awt.Color(51, 153, 255));
		btnXoa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnXoa.setForeground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(new javax.swing.ImageIcon(
				"img\\delete.png")); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXoaActionPerformed(evt);
			}
		});

		btnLamMoi.setBackground(new java.awt.Color(51, 153, 255));
		btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
		btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
		btnLamMoi.setIcon(new javax.swing.ImageIcon(
				"img\\refresh.png")); // NOI18N
		btnLamMoi.setText("Làm mới");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(131, 131, 131)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 298,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 296,
														javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90,
												Short.MAX_VALUE)
										.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(26, 26, 26)
										.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(29, 29, 29).addComponent(btnLamMoi).addGap(57, 57, 57)))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 1426, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 722, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))));
	}// </editor-fold>//GEN-END:initComponents

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnThemActionPerformed

	private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSuaActionPerformed

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnXoaActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLamMoi;
	private javax.swing.JButton btnSua;
	private javax.swing.JButton btnThem;
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnXoa;
	private javax.swing.JComboBox<String> cbbChiTiet;
	private javax.swing.JComboBox<String> cbbTenLoai;
	private javax.swing.JCheckBox chkMaLoai;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable table;
	private javax.swing.JTextField txtMaLoai;

	// End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if (o.equals(btnThem)) {
			GUI_ThemLoaiSanPham guiThemLSP = new GUI_ThemLoaiSanPham();
			guiThemLSP.setVisible(true);
			guiThemLSP.setLocationRelativeTo(null);
			guiThemLSP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			edit = 1;
		} else if (o.equals(btnXoa)) {
			if (table.getSelectedRow() != -1) {
				if (JOptionPane.showConfirmDialog(this, "Có chắc chắn xóa không?", "Cảnh báo",
						JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
					daoLoaiSP.xoaLoaiSP(modelLoaiSP.getValueAt(table.getSelectedRow(), 0).toString());
					modelLoaiSP.removeRow(table.getSelectedRow());
					JOptionPane.showMessageDialog(this, "Xóa thành công");
				}
			} else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn loại sản phẩm cần xóa");
			}
		} else if (o.equals(btnSua)) {
			int row = table.getSelectedRow();
			if (row != -1) {
				GUI_ThemLoaiSanPham guiSuaSP = new GUI_ThemLoaiSanPham();
				guiSuaSP.setVisible(true);
				guiSuaSP.setLocationRelativeTo(null);
				guiSuaSP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
				guiSuaSP.getLbMaLoai().setText(modelLoaiSP.getValueAt(row, 0).toString());
				guiSuaSP.getCbbTenLoai().setSelectedItem(modelLoaiSP.getValueAt(row, 1).toString());
				guiSuaSP.getTxtChiTiet().setText(modelLoaiSP.getValueAt(row, 2).toString());
				;
				edit = 2;
			} else {
				JOptionPane.showMessageDialog(this, "Bạn chưa chọn loại sản phẩm cần sửa");
			}
		} else if (o.equals(btnLamMoi)) {
			txtMaLoai.setText("");
			cbbTenLoai.setSelectedIndex(0);
			cbbChiTiet.setSelectedIndex(0);
			updateTable();
		} else if (o.equals(btnTim)) {
			if (txtMaLoai.getText().equals("") && cbbTenLoai.getSelectedIndex() == 0
					&& cbbChiTiet.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(this, "Nhập thông tin cần tìm kiếm");
			} else {
				String ma = "%" + txtMaLoai.getText().trim() + "%";
				String tl = cbbTenLoai.getSelectedItem().toString();
				String ct = cbbChiTiet.getSelectedItem().toString();
				if (cbbTenLoai.getSelectedIndex() == 0) {
					tl = "";
				}
				if (cbbChiTiet.getSelectedItem().toString().equals("Tất cả")) {
					ct = "";
				}
				if (chkMaLoai.isSelected())
					ma = txtMaLoai.getText().trim();
				if (txtMaLoai.getText().trim().equals(""))
					ma = "%%";
				modelLoaiSP.setRowCount(0);
				ArrayList<LoaiSanPham> dslsp = daoLoaiSP.getLSPTheoDK(ma, tl, ct);
				for (LoaiSanPham lsp : dslsp) {
					modelLoaiSP.addRow(new Object[] { lsp.getMaLoai(), lsp.getTenLoai(), lsp.getChiTiet() });
				}
			}
		}else if(o.equals(cbbTenLoai)) {
			if (!cbbTenLoai.getSelectedItem().toString().equalsIgnoreCase("Tất cả")) {
				cbbChiTiet.removeAllItems();
				for (LoaiSanPham lsp : daoLoaiSP.getLoaiTheoDM(cbbTenLoai.getSelectedItem().toString())) {
					cbbChiTiet.addItem(lsp.getChiTiet());
				}
			}else {
				cbbChiTiet.removeAllItems();
				cbbChiTiet.addItem("Tất cả");
			}
		}
	}
}
