/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import connectDB.ConnectDB;
import dao.Dao_DiaChi;
import dao.Dao_NhaCungCap;
import dao.Dao_PhatSinhMa;
import entity.DiaChi;
import entity.NhaCungCap;

/**
 *
 * @author TuanPC
 */
public class GUI_ThemNhaCungCap extends javax.swing.JFrame implements ActionListener{
	private Vector<String> dsquanHuyen;
	private Vector<String> dsphuongXa;
	private Vector<String> dstinhTP;
	private Dao_DiaChi daoDiaChi;
	private Dao_PhatSinhMa daoPhatSinhMa;
	private Dao_NhaCungCap daoNCC;
    /**
     * Creates new form GUI_ThemNhaCungCap
     */
    public GUI_ThemNhaCungCap() {
    	daoDiaChi = new Dao_DiaChi();
		daoPhatSinhMa = new Dao_PhatSinhMa();
		daoNCC = new Dao_NhaCungCap();
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		initComponents();
		cbbTinhTP.addActionListener(this);
		cbbQuanHuyen.addActionListener(this);
		lbMaNCC.setText(daoPhatSinhMa.getMaNCC());
		lbMaNCC.setForeground(Color.white);
		lbMaNCC.setFont(new Font("Arial", Font.BOLD, 16));
		btnXacNhan.addActionListener(this);
		btnHuy.addActionListener(this);
		btnLamMoi.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbMaNCC = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbbTinhTP = new javax.swing.JComboBox<>();
        cbbPhuongXa = new javax.swing.JComboBox<>();
        cbbQuanHuyen = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 119, 221));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thêm Nhà Cung Cấp");

        jLabel12.setBackground(new java.awt.Color(153, 204, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nhà Sách Thiên Văn");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mã NCC:");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tên NCC:");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Địa Chỉ: ");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SĐT:");

        cbbTinhTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTinhTPActionPerformed(evt);
            }
        });

//        cbbPhuongXa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phường/Xã" }));
//
//        cbbQuanHuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quận/Huyện" }));
//        cbbQuanHuyen.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                cbbQuanHuyenActionPerformed(evt);
//            }
//        });
        dstinhTP = daoDiaChi.getAllTinh();
		cbbTinhTP = new JComboBox(dstinhTP);

		cbbQuanHuyen = new JComboBox<String>();
		cbbQuanHuyen.addItem("Quận/Huyện");

		cbbPhuongXa = new JComboBox<String>();
		cbbPhuongXa.addItem("Phường/Xã");

        btnXacNhan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(51, 102, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon("img\\yes24.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");

        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(51, 102, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\rf24.png")); // NOI18N
        btnLamMoi.setText("Làm Mới");

        btnHuy.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(51, 102, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon("img\\huy24.png")); // NOI18N
        btnHuy.setText("Hủy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cbbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197)
                        .addComponent(btnLamMoi)
                        .addGap(20, 20, 20)
                        .addComponent(btnXacNhan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNCC)))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTinhTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTinhTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTinhTPActionPerformed

    private void cbbQuanHuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbQuanHuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbQuanHuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ThemNhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbbPhuongXa;
    private javax.swing.JComboBox<String> cbbQuanHuyen;
    private javax.swing.JComboBox<String> cbbTinhTP;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbMaNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBtnHuy() {
		return btnHuy;
	}

	public void setBtnHuy(javax.swing.JButton btnHuy) {
		this.btnHuy = btnHuy;
	}

	public javax.swing.JButton getBtnLamMoi() {
		return btnLamMoi;
	}

	public void setBtnLamMoi(javax.swing.JButton btnLamMoi) {
		this.btnLamMoi = btnLamMoi;
	}

	public javax.swing.JButton getBtnXacNhan() {
		return btnXacNhan;
	}

	public void setBtnXacNhan(javax.swing.JButton btnXacNhan) {
		this.btnXacNhan = btnXacNhan;
	}

	public javax.swing.JComboBox<String> getCbbPhuongXa() {
		return cbbPhuongXa;
	}

	public void setCbbPhuongXa(javax.swing.JComboBox<String> cbbPhuongXa) {
		this.cbbPhuongXa = cbbPhuongXa;
	}

	public javax.swing.JComboBox<String> getCbbQuanHuyen() {
		return cbbQuanHuyen;
	}

	public void setCbbQuanHuyen(javax.swing.JComboBox<String> cbbQuanHuyen) {
		this.cbbQuanHuyen = cbbQuanHuyen;
	}

	public javax.swing.JComboBox<String> getCbbTinhTP() {
		return cbbTinhTP;
	}

	public void setCbbTinhTP(javax.swing.JComboBox<String> cbbTinhTP) {
		this.cbbTinhTP = cbbTinhTP;
	}

	public javax.swing.JLabel getjLabel11() {
		return jLabel11;
	}

	public void setjLabel11(javax.swing.JLabel jLabel11) {
		this.jLabel11 = jLabel11;
	}

	public javax.swing.JLabel getjLabel12() {
		return jLabel12;
	}

	public void setjLabel12(javax.swing.JLabel jLabel12) {
		this.jLabel12 = jLabel12;
	}

	public javax.swing.JLabel getjLabel13() {
		return jLabel13;
	}

	public void setjLabel13(javax.swing.JLabel jLabel13) {
		this.jLabel13 = jLabel13;
	}

	public javax.swing.JLabel getjLabel14() {
		return jLabel14;
	}

	public void setjLabel14(javax.swing.JLabel jLabel14) {
		this.jLabel14 = jLabel14;
	}

	public javax.swing.JLabel getjLabel18() {
		return jLabel18;
	}

	public void setjLabel18(javax.swing.JLabel jLabel18) {
		this.jLabel18 = jLabel18;
	}

	public javax.swing.JLabel getjLabel19() {
		return jLabel19;
	}

	public void setjLabel19(javax.swing.JLabel jLabel19) {
		this.jLabel19 = jLabel19;
	}

	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}

	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}

	public javax.swing.JLabel getLbMaNCC() {
		return lbMaNCC;
	}

	public void setLbMaNCC(javax.swing.JLabel lbMaNCC) {
		this.lbMaNCC = lbMaNCC;
	}

	public javax.swing.JTextField getTxtSDT() {
		return txtSDT;
	}

	public void setTxtSDT(javax.swing.JTextField txtSDT) {
		this.txtSDT = txtSDT;
	}

	public javax.swing.JTextField getTxtTenNCC() {
		return txtTenNCC;
	}

	public void setTxtTenNCC(javax.swing.JTextField txtTenNCC) {
		this.txtTenNCC = txtTenNCC;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if (o.equals(cbbTinhTP)) {
			if (!cbbTinhTP.getSelectedItem().toString().equalsIgnoreCase("Tỉnh/Thành phố")) {
				cbbQuanHuyen.removeAllItems();
				dsquanHuyen = daoDiaChi.getAllHuyenTheoTinh(cbbTinhTP.getSelectedItem().toString());
				for (String quan : dsquanHuyen) {
					cbbQuanHuyen.addItem(quan);
				}
			}
		} else if (o.equals(cbbQuanHuyen)) {
			if (cbbQuanHuyen.getItemCount() > 0) {
				if (!cbbQuanHuyen.getSelectedItem().toString().equalsIgnoreCase("Quận/Huyện")) {
					cbbPhuongXa.removeAllItems();
					dsphuongXa = daoDiaChi.getAllPhuongXaTheoTinhVaHuyen(cbbTinhTP.getSelectedItem().toString(),
							cbbQuanHuyen.getSelectedItem().toString());
					for (String phuong : dsphuongXa) {
						cbbPhuongXa.addItem(phuong);
					}
				}
			}
		} else if (o.equals(btnXacNhan)) {
			String maNCC = lbMaNCC.getText();
			String tenNCC = txtTenNCC.getText();
			String sdt = txtSDT.getText();
			String phuong = cbbPhuongXa.getSelectedItem().toString();
			String quan = cbbQuanHuyen.getSelectedItem().toString();
			String tp = cbbTinhTP.getSelectedItem().toString();
			NhaCungCap ncc = new NhaCungCap(maNCC, tenNCC, sdt, new DiaChi(tp, quan, phuong));
			if (GUI_NhaCungCap.edit == 1) {
				if (regex()) {
					if (daoNCC.themNCC(ncc)) {
						JOptionPane.showMessageDialog(null, "Thêm thành công nhà cung cấp " + tenNCC);
						GUI_NhaCungCap.updateTable();
						dispose();
					} else if (!daoNCC.themNCC(ncc)) {
						JOptionPane.showMessageDialog(null, "Số điện thoại đã được dùng");
					}
				}

			} else if (GUI_NhaCungCap.edit == 2) {
				if (regex()) {
					sdt = "";
					if (daoNCC.suaNCC(ncc)) {
						JOptionPane.showMessageDialog(null, "Sửa thành công nhà cung cấp " + tenNCC);
						GUI_NhaCungCap.updateTable();
						dispose();
					} else if (!daoNCC.suaNCC(ncc)) {
						JOptionPane.showMessageDialog(null, "Số điện thoại đã được dùng");

					}
				}

			}

		} else if (o.equals(btnHuy)) {
			dispose();
		} else if (o.equals(btnLamMoi)) {
			txtTenNCC.setText("");
			txtSDT.setText("");
			cbbPhuongXa.setSelectedIndex(0);
			cbbQuanHuyen.setSelectedIndex(0);
			cbbTinhTP.setSelectedIndex(0);
		}
	}
	private boolean regex() {
		String tenNCC = txtTenNCC.getText().trim();
		String sdt = txtSDT.getText().trim();
		String regexTenNCC = "^[ A-Za-za-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]+$";
		String regexSdt = "0[2|3|5|7|8|9][0-9]{8}";
		if (!tenNCC.matches(regexTenNCC)) {
			JOptionPane.showMessageDialog(this, "tên không hợp lệ! ");
			txtTenNCC.requestFocus();
			return false;
		}
		if (!(sdt.length() > 0 && sdt.matches(regexSdt))) {
			JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10 số bắt đầu bằng 02, 03, 05, 07, 08, 09\"");
			txtSDT.requestFocus();
			return false;
		}
		if (cbbTinhTP.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Tỉnh/Thành Phố");
			return false;
		}
		if (cbbQuanHuyen.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Quận/Huyện");
			return false;
		}
		if (cbbPhuongXa.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Phường/Xã");
			return false;
		}

		return true;
	}
}
