/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;

import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;

import connectDB.ConnectDB;
import dao.Dao_ChiTietHoaDon;
import dao.Dao_HoaDon;
import dao.Dao_KhachHang;
import dao.Dao_NhanVien;
import dao.Dao_SanPham;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.SanPham;
import until.Ngay;
import until.Pair;

/**
 *
 * @author Admin
 */
public class GUI_NVThongKeDoanhThu extends javax.swing.JPanel implements ActionListener{
	private Dao_HoaDon dao_HoaDon = new Dao_HoaDon();
	private Dao_ChiTietHoaDon dao_ChiTietHoaDon = new Dao_ChiTietHoaDon();
	private Dao_SanPham dao_SanPham = new Dao_SanPham();
	private DecimalFormat df = new DecimalFormat("#,###,000 VND");
	public Dao_NhanVien dao_NhanVien = new Dao_NhanVien();
	public Dao_KhachHang dao_KhachHang = new Dao_KhachHang();
	private SimpleDateFormat dft = new SimpleDateFormat("yyyy/MM/dd");
	private DefaultTableModel model;
	private double doanhThu;
	private double soVon;
    /**
     * Creates new form GUI_NVThongKeDoanhThu
     */
    public GUI_NVThongKeDoanhThu() {
    	try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        initComponents();
        pnThangNam.setVisible(false);
        jNgayBD.setDateFormatString("dd/MM/yyyy");
        jNgayKT.setDateFormatString("dd/MM/yyyy");
        btnThongKe.addActionListener(this);
        btnInBC.addActionListener(this);
        
        cbLoaiTK.addActionListener((e)->{
        	if(cbLoaiTK.getSelectedIndex()==0) {
        		lbNgayBD.setVisible(true);
        		jNgayBD.setVisible(true);
        		lbNgayKt.setVisible(true);
        		jNgayKT.setVisible(true);
        		pnThangNam.setVisible(false);
        	}else if(cbLoaiTK.getSelectedIndex()==1) {
        		lbNgayBD.setVisible(false);
        		jNgayBD.setVisible(false);
        		lbNgayKt.setVisible(false);
        		jNgayKT.setVisible(false);
        		pnThangNam.setVisible(false);
        	}else if(cbLoaiTK.getSelectedIndex()==2) {
        		lbNgayBD.setVisible(false);
        		jNgayBD.setVisible(false);
        		lbNgayKt.setVisible(false);
        		jNgayKT.setVisible(false);
        		pnThangNam.setVisible(true);
        		lbThang.setVisible(true);
        		jThang.setVisible(true);
        		lbNam.setVisible(true);
        		jNam.setVisible(true);
        	}else if(cbLoaiTK.getSelectedIndex()==3) {
        		lbNgayBD.setVisible(false);
        		jNgayBD.setVisible(false);
        		lbNgayKt.setVisible(false);
        		jNgayKT.setVisible(false);
        		pnThangNam.setVisible(true);
        		lbThang.setVisible(false);
        		jThang.setVisible(false);
        	}
        });
        btnLamMoi.addActionListener((e)->{
        	cbLoaiTK.setSelectedIndex(0); 
        	model.setRowCount(0);
        	jNgayBD.setDate(null);
        	jNgayKT.setDate(null);
        	txtTongHD.setText(""); // tong hoa don
        	lbDoanhThu.setText(""); // doanh thu
        	lbLoiNhuan.setText(""); // loi nhuan
        	lbVon.setText("");// von
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTieuDe = new javax.swing.JLabel();
        pnDSTK = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        pnChucNang = new javax.swing.JPanel();
        pnThangNam = new javax.swing.JPanel();
        lbThang = new javax.swing.JLabel();
        jThang = new com.toedter.calendar.JMonthChooser();
        lbNam = new javax.swing.JLabel();
        jNam = new com.toedter.calendar.JYearChooser();
        btnThongKe = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lbLoaiTK = new javax.swing.JLabel();
        jNgayBD = new com.toedter.calendar.JDateChooser();
        lbNgayBD = new javax.swing.JLabel();
        jNgayKT = new com.toedter.calendar.JDateChooser();
        lbNgayKt = new javax.swing.JLabel();
        cbLoaiTK = new javax.swing.JComboBox<>();
        pnTK = new javax.swing.JPanel();
        pnDoanhThu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbDoanhThu = new javax.swing.JLabel();
        pnLoiNhuan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbLoiNhuan = new javax.swing.JLabel();
        pnVon = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbVon = new javax.swing.JLabel();
        lbTongHD = new javax.swing.JLabel();
        txtTongHD = new javax.swing.JLabel();
        btnInBC = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbTieuDe.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lbTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieuDe.setText("Thống Kê Doanh Thu");

        pnDSTK.setBackground(new java.awt.Color(255, 255, 255));
        pnDSTK.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh sách thống kê"));

        tableTK.setModel(model = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Tên Khách Hàng", "Ngày Lập", "Tổng Tiền", "Lợi nhuận"
            }
        ));
        tableTK.setRowHeight(30);
        tableTK.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(tableTK);

        javax.swing.GroupLayout pnDSTKLayout = new javax.swing.GroupLayout(pnDSTK);
        pnDSTK.setLayout(pnDSTKLayout);
        pnDSTKLayout.setHorizontalGroup(
            pnDSTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
        );
        pnDSTKLayout.setVerticalGroup(
            pnDSTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pnChucNang.setBackground(new java.awt.Color(255, 255, 255));

        pnThangNam.setBackground(new java.awt.Color(255, 255, 255));

        lbThang.setText("Tháng");

        lbNam.setText("Năm");

        javax.swing.GroupLayout pnThangNamLayout = new javax.swing.GroupLayout(pnThangNam);
        pnThangNam.setLayout(pnThangNamLayout);
        pnThangNamLayout.setHorizontalGroup(
            pnThangNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThangNamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThangNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThangNamLayout.createSequentialGroup()
                        .addComponent(lbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNam, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThangNamLayout.createSequentialGroup()
                        .addComponent(lbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jThang, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        pnThangNamLayout.setVerticalGroup(
            pnThangNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThangNamLayout.createSequentialGroup()
                .addGroup(pnThangNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThang, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(pnThangNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNam, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        btnThongKe.setBackground(new java.awt.Color(51, 153, 255));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon("img\\analytics-20.png")); // NOI18N
        btnThongKe.setText("Thống kê");

        btnLamMoi.setBackground(new java.awt.Color(51, 153, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\sync-20.png")); // NOI18N
        btnLamMoi.setText("Làm mới");

        lbLoaiTK.setText("Thống kê theo");

        lbNgayBD.setText("Ngày bắt đầu");

        lbNgayKt.setText("Ngày kết thúc");

        cbLoaiTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ngày", "Ngày hôm nay", "Theo tháng", "Theo năm" }));

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnThangNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnChucNangLayout.createSequentialGroup()
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnChucNangLayout.createSequentialGroup()
                                .addComponent(lbLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLoaiTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChucNangLayout.createSequentialGroup()
                                .addComponent(lbNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnChucNangLayout.createSequentialGroup()
                                .addComponent(lbNgayKt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnChucNangLayout.createSequentialGroup()
                        .addComponent(btnThongKe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoi)))
                .addContainerGap())
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)))
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbNgayKt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(pnThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTK.setBackground(new java.awt.Color(255, 255, 255));

        pnDoanhThu.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("$Doanh Thu");

        lbDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        lbDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnDoanhThuLayout = new javax.swing.GroupLayout(pnDoanhThu);
        pnDoanhThu.setLayout(pnDoanhThuLayout);
        pnDoanhThuLayout.setHorizontalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoanhThuLayout.createSequentialGroup()
                .addGroup(pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDoanhThuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDoanhThuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnDoanhThuLayout.setVerticalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnLoiNhuan.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("$Lợi Nhuận");

        lbLoiNhuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbLoiNhuan.setForeground(new java.awt.Color(255, 255, 255));
        lbLoiNhuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnLoiNhuanLayout = new javax.swing.GroupLayout(pnLoiNhuan);
        pnLoiNhuan.setLayout(pnLoiNhuanLayout);
        pnLoiNhuanLayout.setHorizontalGroup(
            pnLoiNhuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoiNhuanLayout.createSequentialGroup()
                .addGroup(pnLoiNhuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLoiNhuanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLoiNhuanLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbLoiNhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnLoiNhuanLayout.setVerticalGroup(
            pnLoiNhuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoiNhuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLoiNhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnVon.setBackground(new java.awt.Color(255, 102, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("$Vốn");

        lbVon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbVon.setForeground(new java.awt.Color(255, 255, 255));
        lbVon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnVonLayout = new javax.swing.GroupLayout(pnVon);
        pnVon.setLayout(pnVonLayout);
        pnVonLayout.setHorizontalGroup(
            pnVonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVonLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbVon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnVonLayout.setVerticalGroup(
            pnVonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lbTongHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTongHD.setForeground(new java.awt.Color(0, 0, 255));
        lbTongHD.setText("Tổng số hóa đơn:");

        txtTongHD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongHD.setForeground(new java.awt.Color(0, 0, 255));

        btnInBC.setBackground(new java.awt.Color(51, 153, 255));
        btnInBC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInBC.setForeground(new java.awt.Color(255, 255, 255));
        btnInBC.setIcon(new javax.swing.ImageIcon("img\\print-18.png")); // NOI18N
        btnInBC.setText("In báo cáo");

        javax.swing.GroupLayout pnTKLayout = new javax.swing.GroupLayout(pnTK);
        pnTK.setLayout(pnTKLayout);
        pnTKLayout.setHorizontalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTKLayout.createSequentialGroup()
                .addGroup(pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnTKLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(pnLoiNhuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnTKLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnInBC, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnTKLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTKLayout.setVerticalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnLoiNhuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnInBC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDSTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(pnDSTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1429, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInBC;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cbLoaiTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JYearChooser jNam;
    private com.toedter.calendar.JDateChooser jNgayBD;
    private com.toedter.calendar.JDateChooser jNgayKT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser jThang;
    private javax.swing.JLabel lbDoanhThu;
    private javax.swing.JLabel lbLoaiTK;
    private javax.swing.JLabel lbLoiNhuan;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lbNgayBD;
    private javax.swing.JLabel lbNgayKt;
    private javax.swing.JLabel lbThang;
    private javax.swing.JLabel lbTieuDe;
    private javax.swing.JLabel lbTongHD;
    private javax.swing.JLabel lbVon;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnDSTK;
    private javax.swing.JPanel pnDoanhThu;
    private javax.swing.JPanel pnLoiNhuan;
    private javax.swing.JPanel pnTK;
    private javax.swing.JPanel pnThangNam;
    private javax.swing.JPanel pnVon;
    private javax.swing.JTable tableTK;
    private javax.swing.JLabel txtTongHD;
    // End of variables declaration//GEN-END:variables
	public double tinhTongTien(HoaDon hd) {
		double tong = 0;
		ArrayList<ChiTietHoaDon> lsCTHD = dao_ChiTietHoaDon.getAllCTHDTheoMa(((HoaDon) hd).getMaHoaDon());
		for (ChiTietHoaDon ct : lsCTHD) {
			SanPham sp = dao_SanPham.getSPTheoMa(ct.getSanPham().getMaSanPham());
			double giaBan = sp.tinhGiaBan();
			if(dao_SanPham.getSPTheoNgayGiamGia(sp.getMaSanPham(),dft.format(hd.getNgayLap()))!=null) {
				double giamGia =dao_SanPham.getSPTheoNgayGiamGia(sp.getMaSanPham(),dft.format(hd.getNgayLap())).getGiamGia();
				giaBan = sp.tinhGiaBan()*(1-giamGia/100);
			}
			tong += giaBan * ct.getSoLuong();
		}
		return tong + tong * 0.05;
	}
    
    public double von(HoaDon hd) {
    	double von = 0;
		ArrayList<ChiTietHoaDon> lsCTHD = dao_ChiTietHoaDon.getAllCTHDTheoMa(((HoaDon) hd).getMaHoaDon());
		for (ChiTietHoaDon cthd : lsCTHD) {
			SanPham sp = dao_SanPham.getSPTheoMa(cthd.getSanPham().getMaSanPham());
			von+= sp.getGiaNhap()*cthd.getSoLuong();
		}
		return von;
	}
    public void thongKe() {
		doanhThu = 0;
		soVon = 0;
		ArrayList<HoaDon> listHD = dsHoaDon();
		model.setRowCount(0);
		double tong;
		for (HoaDon hd : listHD) {
			tong = tinhTongTien(hd);
			doanhThu = doanhThu + tong;
			soVon = soVon + von(hd);
			model.addRow(new Object[] { hd.getMaHoaDon(),dao_KhachHang.getKhachHangTheoMa(hd.getKhachHang().getMaKhachHang()).getHoTen()
					, hd.getNgayLap(),df.format(tong),df.format(tong-von(hd))});
		}
		lbDoanhThu.setText(df.format(doanhThu));
		lbVon.setText(df.format(soVon));
		lbLoiNhuan.setText(df.format(doanhThu-soVon));
		txtTongHD.setText(tableTK.getRowCount()+"");
	}
    public ArrayList<HoaDon> dsHoaDon(){
    	String maNV = GUI_DangNhap.getTxtTaiKhoan().getText();
    	ArrayList<HoaDon> ds = new ArrayList<HoaDon>();
    	if(cbLoaiTK.getSelectedIndex()==0) {
    		ds = dao_HoaDon.getHDTuNgayDBDenKT(dft.format(jNgayBD.getDate()), dft.format(jNgayKT.getDate()),maNV);
    	}else if(cbLoaiTK.getSelectedIndex()==1) {
    		ds = dao_HoaDon.getDSHDHomNay(LocalDate.now().getYear()+"/"+LocalDate.now().getMonth()+"/"+LocalDate.now().getDayOfMonth(),maNV);
    	}else if(cbLoaiTK.getSelectedIndex()==2) {
    		ds = dao_HoaDon.getDSHDTheoThang(jThang.getMonth()+1+"",jNam.getYear()+"",maNV);
    	}else if(cbLoaiTK.getSelectedIndex()==3) {
    		ds = dao_HoaDon.getDSHDTheoNam(jNam.getYear()+"",maNV);
    	}
    	return ds;
    }
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if(o.equals(btnThongKe)) {
			thongKe();
		}else if (o.equals(btnInBC)) {
			String path = "";
        	JFileChooser j = new JFileChooser(System.getProperty("user.dir") + "\\hoadon\\");
        	j.setDialogTitle("Print file");
        	int x = j.showSaveDialog(this);
        	if(x==JFileChooser.APPROVE_OPTION) {
        		path = j.getSelectedFile().getPath();
        	}
        	
        	com.itextpdf.text.Font textFont = FontFactory.getFont("font/SVN-Arial.ttf", BaseFont.IDENTITY_H,
					BaseFont.EMBEDDED, 10); // 10 is the size
        	com.itextpdf.text.Font textFont12 = FontFactory.getFont("font/SVN-Arial.ttf", BaseFont.IDENTITY_H,
					BaseFont.EMBEDDED, 12); // 12 is the size
        	com.itextpdf.text.Font textFont20 = FontFactory.getFont("font/SVN-Arial.ttf",
					BaseFont.IDENTITY_H, BaseFont.EMBEDDED, 20); // 20 is the size
			com.itextpdf.text.Font textFont24 = FontFactory.getFont("font/SVN-Arial.ttf",
					BaseFont.IDENTITY_H, BaseFont.EMBEDDED, 24); // 24 is the size
			
        	Document doc = new Document();
        	try {
				PdfWriter.getInstance(doc, new FileOutputStream(path+".pdf"));
				
				doc.open();
				Paragraph Name = new Paragraph("Nhà Sách Thiên Văn\n", textFont20);
				Name.setAlignment(Element.ALIGN_LEFT);
				doc.add(Name);
				Paragraph tt = new Paragraph("--------------------------------------------");
				tt.setAlignment(Element.ALIGN_LEFT);
				doc.add(tt);
				
				DateFormat dftt = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
				java.util.Date date = new java.util.Date();
				Paragraph time = new Paragraph(dftt.format(date).toString(),textFont);
				time.setAlignment(Element.ALIGN_RIGHT);
				doc.add(time);
				
				Paragraph DiaChi = new Paragraph("Địa chỉ: 12 Nguyễn Văn Bảo, Quận Gò Vấp, Thành phố Hồ Chí Minh\n",textFont);
				DiaChi.setAlignment(Element.ALIGN_RIGHT);
				doc.add(DiaChi);
				Paragraph SDT = new Paragraph("Số điện thoại: 0338556837\n",textFont);
				SDT.setAlignment(Element.ALIGN_RIGHT);
				doc.add(SDT);
				
				Paragraph tieuDe = new Paragraph("Báo Cáo Doanh Thu\n",textFont24);
				tieuDe.setAlignment(Element.ALIGN_CENTER);
				doc.add(tieuDe);
				Paragraph starLine = new Paragraph(
						"=========================================================================================",
						textFont);
				doc.add(starLine);
				
				SimpleDateFormat dfm = new SimpleDateFormat("dd/MM/yyyy"); 
	        	java.util.Date ngayBD= new java.util.Date();
	        	java.util.Date ngayKT= new java.util.Date();
	        	
	        	ngayBD =  jNgayBD.getDate();
        		ngayKT = jNgayKT.getDate();
        		
        		if (cbLoaiTK.getSelectedIndex() == 2) { // Theo thang
            		int thang = jThang.getMonth()+1;
            		int nam = jNam.getYear();
            		 Pair<Date, Date> range = Ngay.getRangeMonth(thang, nam);
            		 ngayBD = range.getElement0();
            		 ngayKT = range.getElement1();
            		
            	}else if(cbLoaiTK.getSelectedIndex() == 3) { // Theo Nam
            		int nam = jNam.getYear();
            		Pair<Date, Date> range = Ngay.getRangeYear(nam);
           		 	ngayBD = range.getElement0();
           		 	ngayKT = range.getElement1();
            	}else if (cbLoaiTK.getSelectedIndex() == 1) {
            		java.util.Date now = new java.util.Date();
            		ngayBD = now;
            		ngayKT = now;
            	}
				
				// Thông tin ngày báo cáo
				Paragraph paragrapTuNgay = new Paragraph("Từ ngày: " + dfm.format(ngayBD) +"- đến ngày: "+ dfm.format(ngayKT),textFont);
				paragrapTuNgay.setAlignment(Element.ALIGN_CENTER);
				doc.add(paragrapTuNgay);
				doc.add(starLine); 
				
				// Thông tin nhân viên báo cáo
				Paragraph prTenNV = new Paragraph("Tên nhân viên thống kê: "+ dao_NhanVien.getNhanVienTheoMa(GUI_DangNhap.getTxtTaiKhoan().getText()).getHoTen(),textFont);
				Paragraph 	prSDT =	new Paragraph("Số điện thoại: "+ dao_NhanVien.getNhanVienTheoMa(GUI_DangNhap.getTxtTaiKhoan().getText()).getSdt(),textFont);
				doc.add(prTenNV); 
				doc.add(prSDT);
				
				int page = doc.getPageNumber()+1;
				Paragraph prTrang = new Paragraph("Trang số: " +page,textFont);
				prTrang.setAlignment(Element.ALIGN_RIGHT);
				if (page > 1) {
					doc.add(prTrang);
				}
				
				doc.add(new Paragraph("\n"));
				
				PdfPTable tbl = new PdfPTable(new float[] {2.0f,3.0f,5.0f,3.0f,6.0f,6.0f});
				tbl.setWidthPercentage(100.0f);
				// adding header
				PdfPCell c1 = new PdfPCell(new Phrase("STT", textFont));
				c1.setHorizontalAlignment(Element.ALIGN_CENTER);
				tbl.addCell(c1);
				c1 = new PdfPCell(new Phrase("Mã hóa đơn",textFont));
				c1.setHorizontalAlignment(Element.ALIGN_CENTER);
				tbl.addCell(c1);
				c1 = new PdfPCell(new Phrase("Tên khách hàng	",textFont));
				c1.setHorizontalAlignment(Element.ALIGN_CENTER);
				tbl.addCell(c1);
				c1 = new PdfPCell(new Phrase("Ngày lập",textFont));
				c1.setHorizontalAlignment(Element.ALIGN_CENTER);
				tbl.addCell(c1);
				c1 = new PdfPCell(new Phrase("Tổng tiền	",textFont));
				c1.setHorizontalAlignment(Element.ALIGN_CENTER);
				tbl.addCell(c1);
				c1 = new PdfPCell(new Phrase("Lợi nhuận",textFont));
				c1.setHorizontalAlignment(Element.ALIGN_CENTER);
				tbl.addCell(c1);
				for (int i = 0; i < tableTK.getRowCount(); i++) {
					String maHD = tableTK.getValueAt(i, 0).toString();
					String tenKH = tableTK.getValueAt(i, 1).toString();
					String ngayLap = tableTK.getValueAt(i, 2).toString();
					String tongTien = tableTK.getValueAt(i, 3).toString();
					String loiNhuan = tableTK.getValueAt(i, 4).toString();
					tbl.addCell(new Phrase((i+1)+"",textFont));
					tbl.addCell(new Phrase(maHD,textFont));
					tbl.addCell(new Phrase(tenKH,textFont));
					tbl.addCell(new Phrase(ngayLap,textFont));
					tbl.addCell(new Phrase(tongTien,textFont));
					tbl.addCell(new Phrase(loiNhuan,textFont));
				}
				doc.add(tbl);
				Paragraph prDoanhThu = new Paragraph("Tổng doanh thu: "+ lbDoanhThu.getText(),textFont12);
				prDoanhThu.setAlignment(Element.ALIGN_RIGHT);
				doc.add(prDoanhThu);
				Paragraph t = new Paragraph("-----------------------------------------------------");
				t.setAlignment(Element.ALIGN_RIGHT);
				doc.add(t);
				Paragraph prLoiNhuan = new Paragraph("Lợi nhuận: "+ lbLoiNhuan.getText(),textFont12);
				prLoiNhuan.setAlignment(Element.ALIGN_RIGHT);
				doc.add(prLoiNhuan);
				
			} catch (FileNotFoundException | DocumentException e1) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(null, "In không thành công");
			}
        	if(doc != null && x != JFileChooser.CANCEL_OPTION) {
        		JOptionPane.showMessageDialog(this, "In thành công");
			}
        	doc.close();
        	File f = new File(path);
        	openPDF(f.getName());
		}
	}
	 public static void openPDF(String path) {
	        try {
	        	if(new File(System.getProperty("user.dir") + "\\hoadon\\" + path + ".pdf").exists()) {
	        		Process p = Runtime
	        				.getRuntime()
	        				.exec("rundll32 url.dll, FileProtocolHandler " + System.getProperty("user.dir") + "\\hoadon\\" + path +".pdf");
	        	}else {
	        		JOptionPane.showMessageDialog(null, "File is not Exits");
	        	}
	        }catch (Exception e) {
	    		JOptionPane.showMessageDialog(null, e);
	    	}
	    }
}
