/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import connectDB.ConnectDB;
import dao.Dao_DiaChi;
import dao.Dao_NhanVien;
import dao.Dao_PhatSinhMa;
import entity.DiaChi;
import entity.NhanVien;

/**
 *
 * @author TuanPC
 */
public class GUI_ThemNhanVien extends javax.swing.JFrame implements ActionListener{
    /**
     * Creates new form GUI_ThemNhanVien
     */
	private Vector<String> dsquanHuyen;
	private Vector<String> dsphuongXa;
	private Vector<String> dstinhTP;
	private Dao_PhatSinhMa dao_PhatSinhMa;
	private Dao_NhanVien dao_NhanVien;
	private Dao_DiaChi dao_DiaChi;
    public GUI_ThemNhanVien() {
        
        dao_DiaChi = new Dao_DiaChi();
		dao_PhatSinhMa = new Dao_PhatSinhMa();
		dao_NhanVien = new Dao_NhanVien();
		
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		initComponents();
		cbbTinhTP.addActionListener(this);
		cbbQuanHuyen.addActionListener(this);
		lbMaNV.setText(dao_PhatSinhMa.getMaNV());
		lbMaNV.setForeground(Color.white);
		lbMaNV.setFont(new Font("Arial", Font.BOLD, 16));
		btnXacNhan.addActionListener(this);
		btnHuy.addActionListener(this);
		btnLamMoi.addActionListener(this);
		for (String string : dao_DiaChi.getAllTinh()) {
			cbbTinhTP.addItem(string);
		}
		cbbQuanHuyen.addItem("Quận/Huyện");
		cbbPhuongXa.addItem("Phường/Xã");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jcNgaySinhNV = new com.toedter.calendar.JDateChooser();
        txtSDT = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbbTinhTP = new javax.swing.JComboBox<>();
        cbbPhuongXa = new javax.swing.JComboBox<>();
        cbbQuanHuyen = new javax.swing.JComboBox<>();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        cbbChucVu = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(51, 119, 221));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Nhân Viên");

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhà Sách Thiên Văn");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã nhân viên: ");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên nhân viên: ");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày sinh: ");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chức vụ : ");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CCCD/CMND:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Địa Chỉ: ");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SĐT:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Giới tính:");

        cbbTinhTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cbbTinhTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTinhTPActionPerformed(evt);
            }
        });

        cbbPhuongXa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        cbbQuanHuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cbbQuanHuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbQuanHuyenActionPerformed(evt);
            }
        });

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Nam","Nữ"}));

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Quản Lý","Nhân Viên"}));

        btnXacNhan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(51, 102, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon("img\\yes24.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");

        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(51, 102, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon("img\\rf24.png")); // NOI18N
        btnLamMoi.setText("Làm Mới");

        btnHuy.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(51, 102, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon("img\\huy24.png")); // NOI18N
        btnHuy.setText("Hủy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cbbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCCCD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcNgaySinhNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(cbbChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(btnLamMoi)
                                .addGap(20, 20, 20)
                                .addComponent(btnXacNhan)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNV)))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcNgaySinhNV, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTinhTP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTinhTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTinhTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTinhTPActionPerformed

    private void cbbQuanHuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbQuanHuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbQuanHuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ThemNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JComboBox<String> cbbPhuongXa;
    private javax.swing.JComboBox<String> cbbQuanHuyen;
    private javax.swing.JComboBox<String> cbbTinhTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSDT;
    private com.toedter.calendar.JDateChooser jcNgaySinhNV;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if(o.equals(cbbTinhTP)) {
			if (!cbbTinhTP.getSelectedItem().toString().equalsIgnoreCase("Tỉnh/Thành phố")) {
				cbbQuanHuyen.removeAllItems();
				dsquanHuyen = dao_DiaChi.getAllHuyenTheoTinh(cbbTinhTP.getSelectedItem().toString());
				for (String quanHuyen : dsquanHuyen) {
					cbbQuanHuyen.addItem(quanHuyen);
				}
			}
		}else if(o.equals(cbbQuanHuyen)) {
			if(cbbQuanHuyen.getItemCount()>0) {
				if (!cbbQuanHuyen.getSelectedItem().toString().equalsIgnoreCase("Quận/Huyện")) {
					cbbPhuongXa.removeAllItems();
					dsphuongXa = dao_DiaChi.getAllPhuongXaTheoTinhVaHuyen(cbbTinhTP.getSelectedItem().toString(),cbbQuanHuyen.getSelectedItem().toString());
					for (String phuongXa : dsphuongXa) {
						cbbPhuongXa.addItem(phuongXa);
					}
				}
			}
		}else if(o.equals(btnXacNhan)) {
			String ma = lbMaNV.getText();
			String hoTen = txtTenNV.getText().trim();
			Date ngaySinh = new Date(jcNgaySinhNV.getDate().getTime());
			boolean gioiTinh = cbbGioiTinh.getSelectedItem().toString() == "Nữ" ? true : false;
			String cmnd = txtCCCD.getText();
			String sdt = txtSDT.getText();
			String chucVu = cbbChucVu.getSelectedItem().toString();
			String tinh = cbbTinhTP.getSelectedItem().toString();
			String quan = cbbQuanHuyen.getSelectedItem().toString();
			String phuong = cbbPhuongXa.getSelectedItem().toString();
			NhanVien nv = new NhanVien(ma, hoTen, ngaySinh, new DiaChi(tinh, quan, phuong), gioiTinh, cmnd, sdt, chucVu);
			if(GUI_NhanVien.edit==1) {
				if(validData()) {
					if (dao_NhanVien.themNhanVien(nv)) {
						JOptionPane.showMessageDialog(null, "Thêm thành công " + hoTen);
						GUI_NhanVien.updataTable();
						dispose();
					} else if(!dao_NhanVien.themNhanVien(nv)) {
						JOptionPane.showMessageDialog(null,"Số chứng minh hoặc số điện thoại đã được dùng");
					}
				}	
			}else if(GUI_NhanVien.edit==2) {
				if(validData()) {
					if (dao_NhanVien.suaNhanVien(nv)) {
						JOptionPane.showMessageDialog(null, "Sửa thành công " + hoTen);
						GUI_NhanVien.updataTable();
						dispose();
					} 
					else if(!dao_NhanVien.suaNhanVien(nv)) {
						JOptionPane.showMessageDialog(null,"Số chứng minh hoặc số điện thoại đã được dùng");
					}
				}
			}
		}else if(o.equals(btnHuy)) {
			dispose();
		}else if(o.equals(btnLamMoi)) {
			txtTenNV.setText("");
			txtSDT.setText("");
			txtCCCD.setText("");
			cbbChucVu.setSelectedIndex(0);
			cbbGioiTinh.setSelectedIndex(0);
			cbbPhuongXa.setSelectedIndex(0);
			cbbQuanHuyen.setSelectedIndex(0);
			cbbTinhTP.setSelectedIndex(0);
			jcNgaySinhNV.setDate(null);
		}
	}
	private boolean validData() {
		String tenNV = txtTenNV.getText().trim();
		String SDT = txtSDT.getText().trim();
		String CCCD = txtCCCD.getText().trim();
		String regex = "^[aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆ\\n\"\n"
				+ "				+ \"fFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTu\\n\"\n"
				+ "				+ \"UùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ ]+";
		Date ngaySinh = new Date(jcNgaySinhNV.getDate().getTime());
		if(!(tenNV.length()>0 && tenNV.matches(regex))) {
			JOptionPane.showMessageDialog(this, "Họ tên chỉ gồm chữ và khoảng trắng!");
			txtTenNV.requestFocus();
			return false;
		}
		if(LocalDate.now().getYear()-ngaySinh.getDay()<18){
			JOptionPane.showMessageDialog(this, "Nhân viên chưa đủ 18 tuối");
			jcNgaySinhNV.requestFocus();
			return false;
		}
		if(cbbTinhTP.getSelectedIndex()==0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Tỉnh/Thành Phố");
			return false;
		}
		if(cbbQuanHuyen.getSelectedIndex()==0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Quận/Huyện");
			return false;
		}
		if(cbbPhuongXa.getSelectedIndex()==0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Phường/Xã");
			return false;
		}
		if(!(CCCD.length()==12 && CCCD.matches("[0-9 ]+"))) {
			JOptionPane.showMessageDialog(this,"Căn cước công dân phải gốm 12 số");
			txtCCCD.requestFocus();
			return false;
		}
		if(!(SDT.length()>0 && SDT.matches("0[2|3|5|7|8|9][0-9]{8}"))) {
			JOptionPane.showMessageDialog(this,"Số điện thoại gồm 10 số bắt đầu bằng 02, 03, 05, 07, 08, 09\"");
			txtSDT.requestFocus();
			return false;
		}
		return true;
	}

	public javax.swing.JComboBox<String> getCbbChucVu() {
		return cbbChucVu;
	}

	public void setCbbChucVu(javax.swing.JComboBox<String> cbbChucVu) {
		this.cbbChucVu = cbbChucVu;
	}

	public javax.swing.JComboBox<String> getCbbGioiTinh() {
		return cbbGioiTinh;
	}

	public void setCbbGioiTinh(javax.swing.JComboBox<String> cbbGioiTinh) {
		this.cbbGioiTinh = cbbGioiTinh;
	}

	public javax.swing.JComboBox<String> getCbbPhuongXa() {
		return cbbPhuongXa;
	}

	public void setCbbPhuongXa(javax.swing.JComboBox<String> cbbPhuongXa) {
		this.cbbPhuongXa = cbbPhuongXa;
	}

	public javax.swing.JComboBox<String> getCbbQuanHuyen() {
		return cbbQuanHuyen;
	}

	public void setCbbQuanHuyen(javax.swing.JComboBox<String> cbbQuanHuyen) {
		this.cbbQuanHuyen = cbbQuanHuyen;
	}

	public javax.swing.JComboBox<String> getCbbTinhTP() {
		return cbbTinhTP;
	}

	public void setCbbTinhTP(javax.swing.JComboBox<String> cbbTinhTP) {
		this.cbbTinhTP = cbbTinhTP;
	}

	public javax.swing.JTextField getTxtSDT() {
		return txtSDT;
	}

	public void setTxtSDT(javax.swing.JTextField txtSDT) {
		this.txtSDT = txtSDT;
	}

	public com.toedter.calendar.JDateChooser getJcNgaySinhNV() {
		return jcNgaySinhNV;
	}

	public void setJcNgaySinhNV(com.toedter.calendar.JDateChooser jcNgaySinhNV) {
		this.jcNgaySinhNV = jcNgaySinhNV;
	}

	public javax.swing.JTextField getTxtCCCD() {
		return txtCCCD;
	}

	public void setTxtCCCD(javax.swing.JTextField txtCCCD) {
		this.txtCCCD = txtCCCD;
	}

	public javax.swing.JTextField getTxtTenNV() {
		return txtTenNV;
	}

	public void setTxtTenNV(javax.swing.JTextField txtTenNV) {
		this.txtTenNV = txtTenNV;
	}

	public javax.swing.JLabel getLbMaNV() {
		return lbMaNV;
	}

	public void setLbMaNV(javax.swing.JLabel lbMaNV) {
		this.lbMaNV = lbMaNV;
	}
	
}
