/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;

import connectDB.ConnectDB;
import dao.Dao_DiaChi;
import dao.Dao_KhachHang;
import dao.Dao_PhatSinhMa;
import entity.DiaChi;
import entity.KhachHang;

/**
 *
 * @author TuanPC
 */
public class GUI_ThemKhachHang extends javax.swing.JFrame implements ActionListener{
	private Vector<String> dsquanHuyen;
	private Vector<String> dsphuongXa;
	private Vector<String> dstinhTP;
	private Dao_PhatSinhMa dao_PhatSinhMa;
	private Dao_KhachHang dao_KhachHang;
	private Dao_DiaChi dao_DiaChi;
    /**
     * Creates new form GUI_ThemKhachHang
     */
    public GUI_ThemKhachHang() {
        
        dao_DiaChi = new Dao_DiaChi();
		dao_PhatSinhMa = new Dao_PhatSinhMa();
		dao_KhachHang = new Dao_KhachHang();
		
		try {
			ConnectDB.getInstance().connect();
		} catch (SQLException e1) {
			e1.printStackTrace();
		}
		initComponents();
		cbbTinhTP1.addActionListener(this);
		cbbQuanHuyen1.addActionListener(this);
		lbMaKH.setText(dao_PhatSinhMa.getMaKH());
		lbMaKH.setForeground(Color.white);
		lbMaKH.setFont(new Font("Arial", Font.BOLD, 16));
		btnXacNhan1.addActionListener(this);
		btnHuy1.addActionListener(this);
		btnLamMoi1.addActionListener(this);
		for (String string : dao_DiaChi.getAllTinh()) {
			cbbTinhTP1.addItem(string);
		}
		cbbQuanHuyen1.addItem("Quận/Huyện");
		cbbPhuongXa1.addItem("Phường/Xã");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbMaKH = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbbTinhTP1 = new javax.swing.JComboBox<>();
        cbbPhuongXa1 = new javax.swing.JComboBox<>();
        cbbQuanHuyen1 = new javax.swing.JComboBox<>();
        cbbGioiTinh1 = new javax.swing.JComboBox<>();
        btnXacNhan1 = new javax.swing.JButton();
        btnLamMoi1 = new javax.swing.JButton();
        btnHuy1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 119, 221));

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thêm Khách Hàng");

        jLabel12.setBackground(new java.awt.Color(153, 204, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nhà Sách Thiên Văn");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mã khách hàng: ");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tên khách hàng: ");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Địa Chỉ: ");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SĐT:");

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Giới tính:");

        cbbTinhTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTinhTP1ActionPerformed(evt);
            }
        });

        cbbPhuongXa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        cbbQuanHuyen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cbbQuanHuyen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbQuanHuyen1ActionPerformed(evt);
            }
        });

        cbbGioiTinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        btnXacNhan1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnXacNhan1.setForeground(new java.awt.Color(51, 102, 255));
        btnXacNhan1.setIcon(new javax.swing.ImageIcon("img\\yes24.png")); // NOI18N
        btnXacNhan1.setText("Xác Nhận");

        btnLamMoi1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLamMoi1.setForeground(new java.awt.Color(51, 102, 255));
        btnLamMoi1.setIcon(new javax.swing.ImageIcon("img\\rf24.png")); // NOI18N
        btnLamMoi1.setText("Làm Mới");

        btnHuy1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHuy1.setForeground(new java.awt.Color(51, 102, 255));
        btnHuy1.setIcon(new javax.swing.ImageIcon("img\\huy24.png")); // NOI18N
        btnHuy1.setText("Hủy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTinhTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cbbQuanHuyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbPhuongXa1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbGioiTinh1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(btnLamMoi1)
                                .addGap(20, 20, 20)
                                .addComponent(btnXacNhan1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKH)))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbGioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTinhTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPhuongXa1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbQuanHuyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTinhTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTinhTP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTinhTP1ActionPerformed

    private void cbbQuanHuyen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbQuanHuyen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbQuanHuyen1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ThemKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy1;
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnXacNhan1;
    private javax.swing.JComboBox<String> cbbGioiTinh1;
    private javax.swing.JComboBox<String> cbbPhuongXa1;
    private javax.swing.JComboBox<String> cbbQuanHuyen1;
    private javax.swing.JComboBox<String> cbbTinhTP1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JComboBox<String> getCbbPhuongXa1() {
		return cbbPhuongXa1;
	}

	public void setCbbPhuongXa1(javax.swing.JComboBox<String> cbbPhuongXa1) {
		this.cbbPhuongXa1 = cbbPhuongXa1;
	}

	public javax.swing.JComboBox<String> getCbbQuanHuyen1() {
		return cbbQuanHuyen1;
	}

	public void setCbbQuanHuyen1(javax.swing.JComboBox<String> cbbQuanHuyen1) {
		this.cbbQuanHuyen1 = cbbQuanHuyen1;
	}

	public javax.swing.JComboBox<String> getCbbTinhTP1() {
		return cbbTinhTP1;
	}

	public void setCbbTinhTP1(javax.swing.JComboBox<String> cbbTinhTP1) {
		this.cbbTinhTP1 = cbbTinhTP1;
	}

	public javax.swing.JLabel getLbMaKH() {
		return lbMaKH;
	}

	public void setLbMaKH(javax.swing.JLabel lbMaKH) {
		this.lbMaKH = lbMaKH;
	}

	public javax.swing.JTextField getTxtSDT() {
		return txtSDT;
	}

	public void setTxtSDT(javax.swing.JTextField txtSDT) {
		this.txtSDT = txtSDT;
	}

	public javax.swing.JTextField getTxtTenKH() {
		return txtTenKH;
	}

	public void setTxtTenKH(javax.swing.JTextField txtTenKH) {
		this.txtTenKH = txtTenKH;
	}

	public javax.swing.JComboBox<String> getCbbGioiTinh1() {
		return cbbGioiTinh1;
	}

	public void setCbbGioiTinh1(javax.swing.JComboBox<String> cbbGioiTinh1) {
		this.cbbGioiTinh1 = cbbGioiTinh1;
	}

	@Override
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		if(o.equals(cbbTinhTP1)) {
			if (!cbbTinhTP1.getSelectedItem().toString().equalsIgnoreCase("Tỉnh/Thành phố")) {
				cbbQuanHuyen1.removeAllItems();
				dsquanHuyen = dao_DiaChi.getAllHuyenTheoTinh(cbbTinhTP1.getSelectedItem().toString());
				for (String quanHuyen : dsquanHuyen) {
					cbbQuanHuyen1.addItem(quanHuyen);
				}
			}
		}else if(o.equals(cbbQuanHuyen1)) {
			if(cbbQuanHuyen1.getItemCount()>0) {
				if (!cbbQuanHuyen1.getSelectedItem().toString().equalsIgnoreCase("Quận/Huyện")) {
					cbbPhuongXa1.removeAllItems();
					dsphuongXa = dao_DiaChi.getAllPhuongXaTheoTinhVaHuyen(cbbTinhTP1.getSelectedItem().toString(),cbbQuanHuyen1.getSelectedItem().toString());
					for (String phuongXa : dsphuongXa) {
						cbbPhuongXa1.addItem(phuongXa);
					}
				}
			}
		}else if(o.equals(btnXacNhan1)) {
			String ma = lbMaKH.getText();
			String hoTen = txtTenKH.getText().trim();
			boolean gioiTinh = cbbGioiTinh1.getSelectedItem().toString() == "Nữ" ? true : false;
			String sdt = txtSDT.getText();
			String tinh = cbbTinhTP1.getSelectedItem().toString();
			String quan = cbbQuanHuyen1.getSelectedItem().toString();
			String phuong = cbbPhuongXa1.getSelectedItem().toString();
			KhachHang kh = new KhachHang(ma, hoTen, sdt, new DiaChi(tinh, quan, phuong), gioiTinh);
			if(GUI_KhachHang.edit==1) {
				if(validData()) {
					if (dao_KhachHang.themKhachHang(kh)) {
						JOptionPane.showMessageDialog(null, "Thêm thành công " + hoTen);
						GUI_KhachHang.updataTable();
						dispose();
					} else if(!dao_KhachHang.themKhachHang(kh)) {
						JOptionPane.showMessageDialog(null,"Số điện thoại đã được dùng");
					}
				}	
			}else if(GUI_KhachHang.edit==2) {
				if(validData()) {
					if (dao_KhachHang.suaKhachHang(kh)) {
						JOptionPane.showMessageDialog(null, "Sửa thành công " + hoTen);
						GUI_KhachHang.updataTable();
						dispose();
					} 
					else if(!dao_KhachHang.suaKhachHang(kh)) {
						JOptionPane.showMessageDialog(null,"Số điện thoại đã được dùng");
					}
				}
			}
		}else if(o.equals(btnHuy1)) {
			dispose();
		}else if(o.equals(btnLamMoi1)) {
			txtTenKH.setText("");
			txtSDT.setText("");
			cbbGioiTinh1.setSelectedIndex(0);
			cbbPhuongXa1.setSelectedIndex(0);
			cbbQuanHuyen1.setSelectedIndex(0);
			cbbTinhTP1.setSelectedIndex(0);
		}
	}

	private boolean validData() {
		String tenKH = txtTenKH.getText().trim();
		String sdt = txtSDT.getText().trim();
		String regex = "^[ A-Za-za-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]+$";
		if(!(tenKH.length()>0) && tenKH.matches(regex)) {
			JOptionPane.showMessageDialog(this, "Họ tên chỉ gồm chữ và khoảng trắng!");
			txtTenKH.requestFocus();
			return false;
		}
		if(cbbTinhTP1.getSelectedIndex()==0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Tỉnh/Thành Phố");
			return false;
		}
		if(cbbQuanHuyen1.getSelectedIndex()==0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Quận/Huyện");
			return false;
		}
		if(cbbPhuongXa1.getSelectedIndex()==0) {
			JOptionPane.showMessageDialog(this, "Bạn chưa chọn Phường/Xã");
			return false;
		}
		if(!(sdt.length()>0 && sdt.matches("0[2|3|5|7|8|9][0-9]{8}"))) {
			JOptionPane.showMessageDialog(this,"Số điện thoại gồm 10 số bắt đầu bằng 02, 03, 05, 07, 08, 09\"");
			txtSDT.requestFocus();
			return false;
		}
		return true;
	}
    
}
